README.md
=> Update diction for describing transforms in SDK

examples/simple-filter-xml-post/main.go, pkg/edgexsdk/edgexsdk.go, pkg/edgexsdk/edgexsdk_test.go
Addresses allowing to specify MimeType as well as provide Out of the box functions for JSON and XML
=> Support for custom mime type.

examples/simple-filter-xml-mqtt/Dockerfile, examples/simple-filter-xml-mqtt/res/configuration.toml, examples/simple-filter-xml-post/Dockerfile, examples/simple-filter-xml-post/res/configuration.toml, examples/simple-filter-xml/Dockerfile, examples/simple-filter-xml/main.go, examples/simple-filter-xml/res/configuration.toml, go.mod, internal/trigger/http/http.go, makefile, pkg/edgexsdk/edgexsdk.go
Added server.go for 3 end points - the config, the metrics, and for pinging. Added unit testing for server.go
=> System mgmt agent integration

examples/simple-filter-xml-mqtt/res/docker/configuration.toml, examples/simple-filter-xml-post/res/docker/configuration.toml, examples/simple-filter-xml/res/docker/configuration.toml, internal/telemetry/linux_cpu.go, internal/telemetry/telemetry.go, internal/telemetry/windows_cpu.go, internal/trigger/http/http.go, internal/webserver/server.go, internal/webserver/server_test.go
Some files got left out on last  squash
=> hotfix missing files

.gitignore, examples/simple-filter-xml-post/Dockerfile, examples/simple-filter-xml/Dockerfile, internal/constants.go, internal/telemetry/linux_cpu.go, internal/telemetry/telemetry.go, internal/telemetry/unimplemented_cpu.go, internal/webserver/server_test.go, makefile, pkg/transforms/http_test.go
Ensuring docker images run examples with registry option set, and docker profile for config
Copyright header updates
Adding unimplemented_cpu.go
Updating config location in registry
=> Docker and misc code cleanup

README.md, examples/simple-filter-xml-mqtt/main.go, examples/simple-filter-xml-mqtt/res/configuration.toml, examples/simple-filter-xml-mqtt/res/docker/configuration.toml, examples/simple-filter-xml-post/main.go, examples/simple-filter-xml/main.go, examples/simple-filter-xml/res/configuration.toml, examples/simple-filter-xml/res/docker/configuration.toml, internal/common/config.go, internal/webserver/server_test.go, pkg/edgexsdk/edgexsdk.go, pkg/edgexsdk/edgexsdk_test.go
=> Added custom ApplicationSetting so apps can add their on configuration values

pkg/edgexsdk/edgexsdk.go
Signed-off-by: Robert Hakimi <robert.hakimi@intel.com>
=> Channel changes and termination bug fix

go.mod, internal/trigger/messagebus/messaging.go, internal/trigger/messagebus/messaging_test.go
=> Updated to latest go-mod-messaging and fixed imports

appsdk/sdk.go, go.mod
=> Updates for latest go-mod-registry refactoring

go.mod
=> Update to go-mod-registry fix for service crash

makefile
=> Removed -w from gofmt in test target

README.md
https://github.com/edgexfoundry/app-functions-sdk-go/issues/56
=> Updated README.md sample code for syntax errors.

examples/simple-filter-xml-mqtt/main.go, examples/simple-filter-xml-post/main.go, examples/simple-filter-xml/EdgeX Application Function SDK Device Name.postman_collection.json, examples/simple-filter-xml/EdgeX Applications Function SDK.postman_collection.json, examples/simple-filter-xml/main.go
=> Changed simple examples to filter on Random-Float-Generator01

examples/advanced-filter-convert-publish/functions/convert.go, examples/advanced-filter-convert-publish/functions/output.go
=> refactored to use switch and fixed missing '

go.mod
Updating contracts per:
https://github.com/edgexfoundry/go-mod-core-contracts/issues/80
=> updating core contracts

internal/trigger/http/rest.go, internal/trigger/messagebus/messaging.go, pkg/transforms/http.go, pkg/transforms/http_test.go, pkg/transforms/mqtt.go, pkg/transforms/mqtt_test.go
=> Added trace logging of correlation id

go.mod, internal/runtime/runtime.go, internal/runtime/runtime_test.go, internal/trigger/http/rest.go, internal/trigger/messagebus/messaging.go, internal/trigger/messagebus/messaging_test.go
Changed go.mod to pull latest go-mod-messaging and updated code for the breaking changes.
=> Updated to use latest go-mod-messaging

go.mod, internal/runtime/runtime.go
This PR addresses #78 and re-fixes issue that was missed in a previous merge.
=> Updated to use CBOR 1.1.4 and fixed issue missed in merge

appsdk/sdk.go
=> Add logging the configured StartupMsg

go.mod
=> Latest versioned modules for release

appcontext/context.go, internal/trigger/http/rest.go, internal/trigger/messagebus/messaging.go
=> No valid reason to have Trigger exposed on context

.gitignore, examples/simple-cbor-filter/Device Simple Switch commands.postman_collection.json, examples/simple-cbor-filter/Dockerfile, examples/simple-cbor-filter/README.md, examples/simple-cbor-filter/main.go, examples/simple-cbor-filter/res/configuration.toml, examples/simple-cbor-filter/res/docker/configuration.toml, makefile
This PR addresses #92 
See the ReadMe for details on running end to end demonstration
=> Implement example that demonstrate processing CBOR end to end

.gitignore, examples/simple-cbor-filter/Device Simple Switch commands.postman_collection.json, examples/simple-cbor-filter/Dockerfile, examples/simple-cbor-filter/README.md, examples/simple-cbor-filter/main.go, examples/simple-cbor-filter/res/configuration.toml, examples/simple-cbor-filter/res/docker/configuration.toml, makefile
This PR addresses #92 for edinburgh branch
See the ReadMe for details on running end to end demonstration
=> Implement example that demonstrates processing CBOR end to end

README.md, examples/advanced-filter-convert-publish/README.md, examples/simple-filter-xml-mqtt/main.go, examples/simple-filter-xml-post/main.go, examples/simple-filter-xml/EdgeX Application Function SDK Device Name.postman_collection.json, examples/simple-filter-xml/EdgeX Applications Function SDK.postman_collection.json, examples/simple-filter-xml/main.go, examples/simple-filter-xml/res/configuration.toml
This PR addresses #97 on the `edinburgh` branch
Updates for device name changed to Random-Float-Device
Updated advanced example ReadMe to change Device Virtual device profile to use expected floatEncoding and to set min/max values
=> Updated examples for changes to Device Virtual

README.md
=> Remove line about SIGTERM/SIGINT handled by SDK

README.md, appsdk/functions.go, pkg/transforms/compression.go, pkg/transforms/compression_test.go
Address Item No.1 of #110 - Compression
=> feat(compression): Add GZIP + ZLIB Compression Transforms

examples/advanced-filter-convert-publish/Dockerfile, examples/simple-cbor-filter/Dockerfile, examples/simple-filter-xml-mqtt/Dockerfile, examples/simple-filter-xml-post/Dockerfile, examples/simple-filter-xml/Dockerfile, go.mod, makefile
=> build(go-version): Update to go 1.12

README.md, appsdk/functions.go, pkg/transforms/encryption.go, pkg/transforms/encryption_test.go
Address Item No.2 of #110 - Encryption
=> feat(encryption): Adding AES Encryption Transform

README.md
Adding a simple Table of Contents for easy navigation of Readme
=> docs(toc): Adding a Table of Contents

Dockerfile.build, Dockerfile.build-arm64, Jenkinsfile, makefile
Signed-off-by: Tyler Powers <tyler.m.powers@intel.com>
=> build(code-coverage): Add code coverage output to codecov

appsdk/sdk.go
=> fix(log-filename): filename specified in configuration.toml was not being respected. 

README.md
=> docs: fix typo "rigistry" -> "registry" in README

appsdk/sdk.go, examples/advanced-filter-convert-publish/res/configuration.toml, examples/advanced-filter-convert-publish/res/docker/configuration.toml, examples/simple-cbor-filter/res/configuration.toml, examples/simple-cbor-filter/res/docker/configuration.toml, examples/simple-filter-xml-mqtt/res/configuration.toml, examples/simple-filter-xml-mqtt/res/docker/configuration.toml, examples/simple-filter-xml-post/res/configuration.toml, examples/simple-filter-xml-post/res/docker/configuration.toml, examples/simple-filter-xml/res/configuration.toml, examples/simple-filter-xml/res/docker/configuration.toml
This PR addresses #140 for edinburgh branch
=> bugfix(logging): edinburgh: Fix logger initialization for remote logging

appsdk/sdk.go, examples/advanced-filter-convert-publish/res/configuration.toml, examples/advanced-filter-convert-publish/res/docker/configuration.toml, examples/simple-cbor-filter/res/configuration.toml, examples/simple-cbor-filter/res/docker/configuration.toml, examples/simple-filter-xml-mqtt/res/configuration.toml, examples/simple-filter-xml-mqtt/res/docker/configuration.toml, examples/simple-filter-xml-post/res/configuration.toml, examples/simple-filter-xml-post/res/docker/configuration.toml, examples/simple-filter-xml/res/configuration.toml, examples/simple-filter-xml/res/docker/configuration.toml
This addresses PR #140 for the master branch
=> bugfix(logging): Fix logger initialization for remote logging

go.mod
This PR address #129 for master branch
=> bugfix(RaceCondtions): Update to latest go-mod-messaging with race condition fixes

go.mod
This PR addresses #129 for the edinburgh branch
=> bugfix(RaceCondtions): edinbrugh: Update to latest go-mod-messaging with race condition fixes

makefile
=> build(makefile): allow building in gopath by setting GO111MODULE=on

internal/trigger/messagebus/messaging.go
=> fix(logging): When trace enabled, log message for topic subscription is now correct

README.md
=> docs(readme): Updated sample code in readme

appcontext/context.go, appsdk/configurable.go, appsdk/configurable_test.go
=> feat(configurable): Expose MarkAsPushed

appsdk/sdk.go
=> fix(configuration): Utilize protocol from [Service] configuration

internal/webserver/server.go
=> fix(webserver): Timeout wasn't being used

go.mod
Part of fix for https://github.com/edgexfoundry/app-service-configurable/issues/6
=> fix(registry) Update to use latest Registry with fix HasConfiguration

.gitignore, internal/store/db/db.go, internal/store/db/interfaces/store.go, internal/store/db/mongo/store.go, internal/store/db/mongo/store_test.go, internal/store/db/redis/store.go, internal/store/db/redis/store_test.go, internal/store/factory.go, internal/store/models/storedobject.go
Fix #191 
I'm working on the Mongo layer, but realized it was important to make sure my foundation is correct.
Signed-off-by: Brandon Forster <brandonforster@gmail.com>
=> Database and object abstraction for store of store and forward

bin/test-go-mod-tidy.sh, go.mod, makefile
=> build(go.mod): Add running go mod tidy to `make test`

appsdk/sdk.go, examples/simple-filter-xml/main.go, internal/webserver/server.go, internal/webserver/server_test.go
Documentation and Tests to come in a separate PR. 
address: #179
Signed-off-by: Mike Johanson <motifmike@gmail.com>
=> feat(webserver): Expose webserver to enable developer to add routes.

appcontext/context.go, appcontext/context_test.go, appsdk/configurable.go, appsdk/configurable_test.go, examples/simple-filter-xml-mqtt/main.go, examples/simple-filter-xml-post/main.go, pkg/transforms/http.go, pkg/transforms/http_test.go, pkg/transforms/mqtt.go, pkg/transforms/mqtt_test.go
Applies to MQTT & HTTP exports.
First of a few PRs for #111
=> feat(transforms): Add ability to persist data for later retry to export functions

appcontext/context_test.go, go.mod, pkg/startup/endpoint.go
Latest CommandClient now has the "byNames" APIs for sending GET or PUT commands
=> feat(contracts): Update to latest Core Contracts for new Command APIs

go.mod, internal/store/contracts/storedobject.go, internal/store/db/db.go, internal/store/db/mongo/models/storedobject.go, internal/store/db/mongo/store.go, internal/store/db/mongo/store_test.go, internal/store/db/redis/models/storedobject.go, internal/store/db/redis/models/storedobject_test.go, internal/store/db/redis/store.go, internal/store/db/redis/store_test.go, internal/webserver/server_test.go
Fixes #193 
This PR also addresses some follow on concerns raised by having a second driver that weren't noticed when building the Mongo driver.
=> feat(store): Add Redis driver

Makefile, appsdk/sdk.go, appsdk/sdk_test.go, internal/runtime/runtime.go, internal/runtime/runtime_test.go, internal/runtime/storeforward.go, internal/runtime/storeforward_test.go, internal/store/db/interfaces/mocks/StoreClient.go, internal/trigger/messagebus/messaging_test.go
Implement the core `runtime` portion of Store and Forward. The DB Abstraction, Mongo DB, Configuration and Functions portions have already been implemented and committed.
One of many for #111
Previous completed PRs for #111:
- #213
- #211
- #210
Related PRs:
- #204
- #194
- #212
=> feat(runtime): Store and Forward core implementation in runtime package.

appsdk/sdk.go, appsdk/sdk_test.go, internal/runtime/storeforward.go, internal/telemetry/telemetry.go, internal/trigger/http/rest.go, internal/trigger/messagebus/messaging.go, internal/trigger/messagebus/messaging_test.go, internal/trigger/trigger.go
Implement the appsdk and context portion of Store and Forward. The Runtime, DB Abstraction, Mongo DB, Configuration and Functions portions have already been implemented, committed & merged.
Documentation and misc will be the final PR for SDK. Then followed up by PR foe app-service-configurable.
One of many for #111
Previous PRs for #111:
#226
#213
#211
#210
Related PRs:
#204
#194
#212
=> feat(appsdk): appsdk and context changes for Store and Forward.

.chglog/CHANGELOG.tpl.md, .chglog/config.yml, CHANGELOG.md
=> docs: changelog information

.github/PULL_REQUEST_TEMPLATE.md
=> docs: PR Template

README.md, appsdk/sdk.go, appsdk/sdk_test.go, examples/advanced-filter-convert-publish/res/configuration.toml, examples/advanced-target-type/res/configuration.toml, examples/simple-cbor-filter/res/configuration.toml, examples/simple-filter-xml-mqtt/res/configuration.toml, examples/simple-filter-xml-post/res/configuration.toml, examples/simple-filter-xml/res/configuration.toml, examples/simple-filter-xml/res/docker/configuration.toml, internal/common/config.go, internal/constants.go, internal/runtime/storeforward.go, internal/store/db/db.go, internal/store/db/mongo/store.go, internal/store/db/redis/store.go, internal/webserver/server.go, internal/webserver/server_test.go
This PR address or fix the issue #232 .   
=> feat(appsdk): Change configuration intervals to duration strings

.gitignore, Attribution.txt, Makefile, bin/test-attribution-txt.sh
Attribution.txt file is missing.
Issue Number: #248 
Attribution.txt file has been added
makefile `test` target has been update to validate Attribution.txt file is up to date.
=> doc(Attribution): Add missing Attribution.txt file and update makefile test target

README.md
- [ x ] The commit message follows our guidelines: https://github.com/edgexfoundry/app-functions-sdk-go/blob/master/.github/CONTRIBUTING.md
Issue Number:
#161 
Section is now visible in the ToC
=> docs: Add webserver usage to ToC

README.md
Example code will panic when LoggingClient is not initialized due to other error in bootstrap process.
Issue Number: #245 
Example code will not panic if LoggingClient not initialized
=> bug(README): Fix example code in README to not panic if LoggingClient not initialized

.github/PULL_REQUEST_TEMPLATE.md
=> docs: Update PR Template based on feedback

Dockerfile.build, Jenkinsfile, go.mod
=> build: Update relevant files in app-functions-sdk-go for Go 1.13.

Dockerfile.build, Jenkinsfile, Jenkinsfile.sandbox, go.mod
Closes issue #280
Go 1.12
Go 1.13
=> build: update go version to 1.13

pkg/transforms/batch_test.go
Signed-off-by: Michael Johanson <michael.johanson@intel.com>
- [S] Tests for the changes have been added (for bug fixes / features)
Test is failing for Batch and send intermittently
Issue Number: #289
Tests pass successfully by increasing delay in test for batch and send
=> test: fix timing issue with Batch transform test

README.md
=> docs: batch documentation created

go.mod
Signed-off-by: Brandon Forster <me@brandonforster.com>
[There is a known issue with the URLClient implementation in core-contracts 0.1.48.](https://github.com/edgexfoundry/go-mod-core-contracts/issues/220) 0.1.51 corrects the issue and this should be updated to that version.
Issue Number: Contracts [#220](https://github.com/edgexfoundry/go-mod-core-contracts/issues/220)
=> bug(urlclient): Update contracts version to fix bug in URLClient.

pkg/transforms/batch_test.go
addresses #289
Signed-off-by: Michael Johanson <michael.johanson@intel.com>
Added second wait group for ensuring correct order in test case
=> test: fix race condition in batch tests

go.mod
Latest go-mod-core-contracts has added ValueType, MediaType, & FloatEncoding to Reading
Reading model didn't contain ValueType, MediaType or FloatEncoding
Issue Number:  #300
Reading model now contains ValueType, MediaType or FloatEncoding
=> feat(core contracts): Upgrade to latest Core Contracts for Reading enhancements

internal/trigger/messagebus/messaging.go
Issue Number: #298 
Messagebus trigger now calls connect
Tested new changes with both MQTT and ZeroMQ with success
=> Invoke connect on initialization

go.mod
MQTT messages are sent via the MQTT client provided in the `github.com/eclipse/paho.mqtt.golang` module. 
Issue Number: #279 
MQTT messages are sent via the MQTT client provided by `go-mod-messaging` which eliminates the need for most of the setup and management of the underlying client, since it is handled in `go-mod-messaging`
A new integration test has been added, which will be executed only when the `brokerRunning` tag is provided during a test execution. These changes can be verified by executing the newly added integration test.
=> Update To Use go-mod-messaging MQTT Client

pkg/transforms/batch.go, pkg/transforms/batch_test.go
closes #310
Batch properly sends data upon threshold being reached
No
=> fix(batch): 2nd batch hanging in count mode

internal/security/secret.go, internal/security/secret_test.go
This is to fix bug #317: SecretStore initialization retry loop breaks backwards compatibility
- Change initialization logic to call the initialzation of secret client at least once regardless of configuration SecretStore_AdditionalRetryAttempts is given or not
- Refactor the retry loop logic better
- Unit tests added for various AdditionalRetryAttempts numbers
Fixes: #317
The current retry loop logic skips the initialization of secret client if AdditionalRetryAttempts from configuration is omitted.  Initialization of secret client should perform at least once, at the beginning.
Issue Number: #317
Now, the initialization of secret …
=> fix(SecretClient): Initialization of secret client retry logic

appsdk/configurable.go
Issue Number: #319 
ASC can now leverage the functions included in this PR (batch, jsonlogic, httpw/secrets)
=> Update Configurable w/ latest functions

README.md, appsdk/configurable.go, internal/security/credentials.go, internal/security/secret.go, internal/security/secret_test.go, pkg/transforms/mqttsecret.go, pkg/transforms/mqttsecret_broker_test.go, pkg/transforms/mqttsecret_test.go
=> feat(mqttsecrets): secure access of secrets for mqtt

.github/PULL_REQUEST_TEMPLATE.md
remove contribution guidelines from PR checklist since commitlint checks this
Issue Number:
=> docs(pr-template): remove contribution guidelines from PR checklist

appsdk/configurable.go, appsdk/configurable_test.go
=> feat(configurable): add mqtt secret support

go.mod, internal/runtime/runtime.go, internal/runtime/runtime_test.go
Fixes [#305](https://github.com/edgexfoundry/app-functions-sdk-go/issues/305)
refact(CBOR): Replace ugorji/go with fixmacker/cbor
Issue Number:  [#305](https://github.com/edgexfoundry/app-functions-sdk-go/issues/305)
Refactoring, no change in behavior.
none
=> refact(CBOR): Replace ugorji/go with fixmacker/cbor

.github/semantic.yml
Type and scope are not conforming to standard conventional commits. 
Issue Number:
commits type will be validated against valid list of types. Scope will be out of scope for now. 
This will not be used until devops updates the bot to the latest version.
=> ci: improve conventional commit conformance

appsdk/sdk.go, appsdk/sdk_test.go
env override of profile not properly impacting the service key which contains profile replacement placeholder.
Issue Number: #334
env override of profile properly changes the service key which contains profile replacement placeholder.
=> fix(profile): Set profile properly in service's service key when env override used

appsdk/sdk.go
closes 
edgex-service environment variable no longer supported, which is a breaking change missed when moving to common bootstrap.
Issue Number: https://github.com/edgexfoundry/app-service-configurable/issues/63
edgex-service environment variable is again supported, but deprecated.
=> fix: Handle deprecated edgex_service env variable

go.mod, internal/trigger/messagebus/messaging.go
No support for Redis Stream Message Bus
Issue Number: #333
No have ability to use Redis Stream Message Bus
=> feat: Integrate with new redis streams message bus implementation

appsdk/configupdates.go, internal/bootstrap/handlers/storeclient.go, internal/bootstrap/handlers/version.go
Wrap version check and DB connection in a retry loop instead of sending an error
close #339
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
Issue Number: #339
=> fix(retry loop): Wrap version check and DB connection in a retry loop

.github/semantic.yml
- [] Build related changes
Issue Number:
=> ci: allow merge from master in git history

pkg/transforms/batch_test.go
intermittent unit test failure on ARM
Issue Number: #351
Hopefully no more intermittent unit test failure on ARM
=> fix: Added longer sleep to fix intermittent unit test failure on ARM

appsdk/configupdates.go, pkg/transforms/batch_test.go
InsecureSecrets nil in updated config cause actual updated to not be processed.
Lack of proper error handling and logging
Issue Number: #353
- Look for when InsecureSecrets nil in updated config nil and skip processing it
- Properly examine all other possible changes and then default to processing Pipeline updates
- Added better error handling and logging when updates are processed
=> fix: Implement smarter configuration update processing

pkg/transforms/batch_test.go
periodic Batch and Send unit test failure on ARM CI jobs
Issue Number: #360
Hopefully no more CI job failures do Batch and Send unit tests
=> fix: Add more sleep time to Batch and Send unit test to fix ARM CI failures

go.mod
Using old version of go-mod-core-contracts that had bug in it related to validation when binary value has been removed.
Issue Number: #362
Using new version of go-mod-core-contracts that has fix for bug related to validation when binary value has been removed.
=> build: Updated to latest go-mod-core-contracts for bug fix

appsdk/configurable.go, appsdk/configurable_test.go, pkg/transforms/filter.go, pkg/transforms/filter_test.go
feat: Add ability to Filter functions to reverse the logic to filter out specified names
close #<359#>
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
Issue Number:
359
Added the ability to filter out specified devices and values
A new filterout parameter has been added to the filter parameters. This is how a filter will know what type of filtering to use. By default the filterout parameter will be set to false.
=> feat: Add ability to Filter functions to reverse the logic to filter out specified names

pkg/transforms/filter.go
close #359
Signed-off-by: Brian McGinn <brian.mcginn@intel.com>
Issue Number:
359
=> fix: fixed log message formatting

.github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: James Gregg <james.r.gregg@intel.com>
Update PR template to add new question for new dependencies (e.g. imports / modules) as per the decision in the Architect's meeting 06/15/2020
Issue Number:
=> docs: update pr template to include dependencies question

.github/semantic.yml
Addresses #410
Issue Number: #410 
Validates scope if scope has been added to commit message
no
no
=> ci: add scopes to pr-bot

go.mod, internal/store/db/db.go, internal/store/db/mongo/models/storedobject.go, internal/store/db/mongo/models/storedobject_test.go, internal/store/db/mongo/store.go, internal/store/db/mongo/store_test.go, internal/store/factory.go
Mongo implementation code was prematurely removed 
Issue Number:  #412
Restored Mongo implementation code
No
Just had to restore all the files under the Store folder and tested with ASC with Store and Forward enabled using mongodb.
=> revert(store-forward): remove of Mongo implementation

.github/semantic.yml
Issue Number: 417
Dependabot PRs will now pass commit checks
No
No
=> ci: update scope to include "deps" in semantic.yml

appsdk/sdk.go
Signed-off-by: charles-knox-intel <44684517+charles-knox-intel@users.noreply.github.com>
As described in https://github.com/edgexfoundry/app-functions-sdk-go/issues/423 and https://github.com/edgexfoundry/app-service-configurable/issues/87, there are no service startup messages.
Issue Number: #423 
Service startup messages should appear due to the message bootstrap handler being added.
No new imports that are not already present in `go.mod`.
Nope.
=> feat: add message bootstrap handler, fixes #423

go.mod, internal/v2/controller/http/controller.go, internal/v2/controller/http/controller_test.go, internal/v2/routes.go, internal/webserver/server.go
fixes: #432
Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>
Issue Number:
#432 
add the V2 ping endpoint and controller/http layer
No
=> feat: Implement V2 Ping endpoint and V2 layers

internal/v2/controller/http/controller.go, internal/v2/controller/http/controller_test.go, internal/v2/routes.go
No v2 Version endpoint
Issue Number: #429
V2 Version endpoint implemented
No
=> feat: Add V2 Version endpoint

internal/v2/controller/http/controller.go, internal/v2/controller/http/controller_test.go, internal/v2/routes.go
fixes: #430
Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>
there is no existing no V2 Metrics API
Issue Number:
#430 
Implements V2 Metrics API
no
no
=> feat: Implement V2 Metrics endpoint

internal/v2/controller/http/controller.go, internal/v2/controller/http/controller_test.go, internal/v2/routes.go, internal/webserver/server.go
No V2 Config endpoint implementation
Issue Number:  #431
V2 Config endpoint now implemented
No
=> feat: Implement V2 Config endpoint

internal/constants.go, internal/trigger/http/rest.go, internal/webserver/server.go, internal/webserver/server_test.go, openapi/v2/app-functions-sdk.yml
No V2 trigger endpoint 
Issue Number: #427
As agreed V2 uses same implementation as V1
V2 Swagger for Trigger has been update to remove use of DTOs
No
=> feat: Implement V2 Trigger endpoint

appsdk/configurable.go, appsdk/configurable_test.go, go.mod, pkg/transforms/batch.go, pkg/transforms/conversion.go, pkg/transforms/jsonlogic.go, pkg/transforms/tags.go, pkg/transforms/tags_test.go, pkg/util/helpers.go
None.
Issue Number:  #455 & #369
AddTags function now available to custom app services and to App Service Configurable. 
Also had to fix issue with XML marshaling due to error thrown due to `map` not supported by XML marshal provided in Go.
Also added missing copyright headers to other transform files.
No
=> feat: Implement transform to add Tags to Event

pkg/transforms/mqtt.go, pkg/transforms/mqttsecret.go
race case exist when setting up and connecting to the MQTT export client
Issue Number:  #471
Mutex locks added around setting up and connecting to the MQTT export client
No
=> fix: Add locking around MQTT client setup and around connecting to avoid race conditions.

internal/trigger/messagebus/messaging_test.go
After analyzing those data races as listed in #488, there are two
variables shall be in atomic operation to avoid data races:
1. transformWasCalled inside TestInitializeAndProcessEventWithNoOutput
2. transformWasCalled inside TestInitializeAndProcessEventWithOutput
This commit update these two variables from bool to common.AtomicBool to
aovid the data races.
Signed-off-by: Jude Hung <jude@iotechsys.com>
Issue Number:
#488 
Clean up all these data races detected from messagebus unit test function
No.
https://golang.org/doc/articles/race_detector.html#:~:text=A%20data%20race%20occurs%20when,Go%20Memory%20Model%20for%20details.
=> fix: Data races detected from messagebus unit test #488

.github/workflows/go.yml, Dockerfile.build, Jenkinsfile, go.mod
Issue Number: #463
Now uses Go 1.15 
no
=> build: Switch to use Go 1.15

go.mod, internal/v2/controller/http/controller.go, internal/v2/dtos/requests/secrets.go, internal/v2/dtos/requests/secrets_test.go
V2 API used old errors definitions from go-mod-core-contracts V2 which no longer exist.
Issue Number: #487
Now uses new errors mechanism from go-mod-core-contracts
no
=> refactor: Refactor V2 API to use new errors mechanism for go-mo-core-contracts

.github/dependabot.yml
=> build: Enable DependaBot via YML file rather than external BOT

appsdk/configupdates.go, appsdk/sdk.go
`edgexClients` is not exposed, i.e. private property.
Issue Number: #446 
`EdgexClients` is now exposed, i.e. public property
no
=> feat(sdk): Expose SDK EdgeX clients

internal/trigger/mqtt/mqtt.go
Topic not re-subscribed to when auto reconnect occurs
Issue Number: #531
Topic is subscribed to after any connect, initial or auto
no
=> fix(triggers): MQTT subscribe via onConnect handler so re-subscribe on auto-reconnect

go.mod, internal/v2/controller/http/controller.go, internal/v2/controller/http/controller_test.go, internal/v2/dtos/requests/secrets_test.go
DependaBot PR builds fail due to recent name change in go-mod-core-contracts
Issue Number: #542
No build failures with latest go-mod-core-contracts
no
=> build: Use latest go-mod-core-contracts and fix build errors due to name change

pkg/transforms/batch_test.go
TestBatchInTimeAndCountMode_TimeElapsed fails intermittently in CI.
Issue Number:  #548
TestBatchInTimeAndCountMode_TimeElapsed no longer fails intermittently in CI, hopefully :-)
no
=> fix: Adjust timing so test doesn't fail intermittently

appsdk/configurable.go, pkg/transforms/conversion_test.go, pkg/transforms/http.go, pkg/transforms/http_test.go
HTTP Export only allowed POST to the target URL via the HTTPPost pipeline function.
Issue Number: #516
HTTP Export allows POST & PUT to the target URL via the HTTPPost & HTTPPut pipeline functions.
no
=> feat: Add ability to export via HTTP PUT with secret header support

appcontext/context_test.go, appsdk/sdk_test.go, internal/bootstrap/handlers/version_test.go, internal/runtime/runtime_test.go, internal/security/client/vaultclient_test.go, internal/security/credentials_test.go, internal/security/secret_test.go, internal/trigger/messagebus/messaging_test.go, internal/webserver/server_test.go, pkg/transforms/tags_test.go
File logging is used and causes unneeded local log files to be created.
Test results are not cluttered with log messages.
Issue Number:  #477
Mock Logger doesn't log anything, so test results are no longer cluttered with log messages.
No
=> refactor: Change all unit tests to use logger.NewMockCient()

go.mod, internal/v2/controller/http/controller.go
NewBaseResponseWithoutMessage has been removed from go-mod-core-contracts
Issue Number: #556 
Now call NewBaseResponse with empty string for the message parameter
no
=> refactor: Replace calling NewBaseResponseWithoutMessage with NewBaseResponse

.github/semantic.yml
closes #495
Issue Number: #495 
N/A
=> ci: update scopes and types for conventional commits

Dockerfile.build
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
Issue Number: #609
No
=> ci: standardize dockerfiles

appcontext/context.go, appcontext/context_test.go, appsdk/configurable.go, appsdk/configurable_test.go, internal/runtime/runtime.go, internal/runtime/runtime_test.go, internal/runtime/storeforward.go, internal/runtime/storeforward_test.go, internal/store/contracts/storedobject.go, internal/store/db/redis/models/storedobject.go, internal/store/db/redis/models/storedobject_test.go, pkg/transforms/coredata.go, pkg/transforms/coredata_test.go
MarkAsPush feature exists in SDK
Issue Number:  #594
MarkAsPush feature no longer exists in SDK
no
=> feat: Remove MarkAsPushed feature

appsdk/backgroundpublisher.go, appsdk/sdk.go, appsdk/trigger.go, appsdk/triggerfactory.go, appsdk/triggerfactory_test.go, go.mod, internal/common/config.go, internal/runtime/runtime.go, internal/runtime/runtime_test.go, internal/trigger/http/rest.go, internal/trigger/http/rest_test.go, internal/trigger/messagebus/messaging.go, internal/trigger/messagebus/messaging_test.go, internal/trigger/mqtt/mqtt.go, swagger.json
v0.x.x of go-mod-messaging is used.
Issue Number: #637
v2.x.x of go-mod-messaging is now used.
no
=> build: Update to use go-mod-messaging v2

internal/runtime/runtime.go
Event Tags are not part of the Debug logging of Event details
Issue Number:  #700
Event Tags are now part of the Debug logging of Event details
no
=> feat: Add debug logging of the Event Tags

appsdk/configurable.go, appsdk/configurable_test.go, pkg/transforms/conversion_test.go, pkg/transforms/encryption.go, pkg/transforms/encryption_test.go, pkg/transforms/http_test.go
Encryption key is in function configuration via app-service-configuration or factory function for custom services.
Issue Number:  #372
Encryption key can now additionally be pulled from the Secret Store.
no
=> feat: Add secrets capability to Encryption pipeline function

internal/runtime/runtime.go, internal/runtime/runtime_test.go
DTO validation error results in 500 (Internal Server Error) status code, rather than the expected 400 (Bad Request) status code.
Issue Number: #702
DTO validation error results in proper 400 (Bad Request) status code.
=> fix: Return 400 (BadRequest) on DTO validation failure

internal/runtime/runtime.go
CBOR add event requests are explicitly validated, which is now redundent.
Issue Number: #694
Removed code that validates event request when it is CBOR encode. Validation now done as part of decoding the request.
no
=> refactor: Remove unneeded call to validate CBOR encoded Event request

app-service-template/go.mod, go.mod, internal/appfunction/context.go, internal/appfunction/context_test.go, internal/runtime/runtime.go
closes #749
ApiVersion has been remove from Reading DTO, but sdk code and tests still reference it.
Issue Number:
All references to Reading DTO ApiVersion have been removed 
no
=> refactor: Adjust code for latest go-mod-core contracts changes

internal/appfunction/context.go, pkg/interfaces/context.go
Adds context.ResponseData() to public interface, making it available for
use in custom triggers
Issue Number:
#758
=> fix(v2): Expose Response Data

app-service-template/go.mod, go.mod, internal/appfunction/context.go, internal/runtime/runtime.go, internal/runtime/runtime_test.go, internal/trigger/messagebus/messaging_test.go, pkg/transforms/conversion_test.go, pkg/transforms/filter.go, pkg/transforms/responsedata_test.go
Old core contracts used still has Created and Modified on the Event DTO
Issue Number: #770
Updated to latest core contracts which has removed Created and Modified from the Event DTO
Code and unit tests updated to remove Created and Modified
No
=> refactor: Update code for Created & Modified removed from Event DTO

internal/bootstrap/handlers/version.go
using /api/version endpoint for the Version check
Issue Number: #777
Now using /api/v2/version endpoint for the Version check
no
=> refactor: Update Version Check to use V2 endpoint

go.mod, internal/constants.go
Currently use `/1.0/` path hard code in the SDK
Issue Number: #768
Now using the `/2.0/` path set by go-mod-bootstrap
BREAKING CHANGE: Consul configuration now under the `/2.0/` path
no
=> refactor: Switch to 2.0 Consul path

.github/workflows/go.yml
Work flow has a `build` step that uses `go build`. This is now failing after the addition of the template app service.
Issue Number: none
Removed `build` step since this repo only needs the `test` step, which uses the `make test` target.
=> build: Fix workflow for GitHub actions

.github/workflows/codeql-analysis.yml
=> ci: add code scanning

Dockerfile.build, app-service-template/Makefile, go.mod
closes 
Files specified Go 1.15
Issue Number: #821
Files now specify Go 1.16
no
=> ci: Update files for Go 1.16

app-service-template/go.mod, go.mod
closes 
MessageBus Secret validation fails in non-secure mode
Issue Number: #831
MessageBus Secret validation works in non-secure mode
=> fix: Fix Secure MessageBus Secret validation for non-secure mode

internal/trigger/mqtt/mqtt.go
Error message missing .ExternalMqtt subsection 
Issue Number:  #835
Error message now has .ExternalMqtt subsection 
no
=> fix: Added missing .ExternalMqtt subsection to error log message

internal/controller/rest/controller.go, internal/webserver/server.go
Error message has wrong setting name
Add secret has obsolete code to ensure path has correct slashes.
Issue Number: #868 & #869
Error message corrected
Obsolete code removed.
no
=> fix: Fix incorrect error message and remove obsolete code

pkg/transforms/mqttsecret.go, pkg/transforms/mqttsecret_test.go
Allow user to initialize MQTTSecretSender with a formatting function
that builds a final publish topic from the configured topic and the
input parameters to the MQTTSend function.  Also change default behavior
to allow for placeholders for context values to be used in configured
topic, eg:
"topic/{context-key}" will publish to
"topic/current-value-at-context-key-for-this-pipeline-execution" on each call
Currently MQTTSender publishes directly to the topic string configured.
Issue Number:
#871
MQTTSender will replace {my-key} with the value found in the context at my-key by default.  It will also be possible to configure a custom …
=> feat(transforms): Add Topic Formatting Capability to MQTTSecretSender

internal/appfunction/context.go, internal/appfunction/context_test.go, pkg/interfaces/context.go, pkg/transforms/http.go, pkg/transforms/http_test.go, pkg/transforms/mqttsecret.go, pkg/transforms/mqttsecret_test.go, pkg/transforms/stringvaluesformatter.go, pkg/transforms/stringvaluesformatter_test.go
Issue Number: #876
URL in http sender will be formatted in similar fashion to the topic formatting in MQTTSecretSender
=> feat(sdk): Add URL Formatting To HTTP Sender

internal/app/configurable.go
closes
Parse new parameters but never use them to configure HttpExport
Issue Number:  #879
Now use new parameters to configure HttpExport
no
=> fix: Use new multi-export parameters when configuring HttpExport

app-service-template/go.mod, app-service-template/res/configuration.toml, go.mod, internal/app/configurable.go, internal/app/configurable_test.go, internal/app/service.go, internal/app/service_test.go, internal/appfunction/context.go, internal/appfunction/context_test.go, internal/bootstrap/container/clients.go, internal/bootstrap/handlers/clients.go, internal/bootstrap/handlers/clients_test.go, pkg/interfaces/context.go, pkg/interfaces/mocks/AppFunctionContext.go, pkg/interfaces/mocks/ApplicationService.go, pkg/interfaces/service.go, pkg/transforms/batch_test.go, pkg/transforms/compression_test.go, pkg/transforms/conversion_test.go, pkg/transforms/coredata.go, pkg/transforms/coredata_test.go, pkg/transforms/encryption_test.go, pkg/transforms/filter_test.go, pkg/transforms/http_test.go, pkg/transforms/jsonlogic_test.go, pkg/transforms/mqttsecret_test.go, pkg/transforms/responsedata_test.go, pkg/transforms/tags_test.go, pkg/transforms/testmain_test.go
Using V1 clients (except Command) and PushToCore is based on V1
Issue Number:  #370 & #721
Now using V2 clients and PushToCore has been refactored to conform to V2 API/DTOs
BREAKING CHANGE: PushToCore signatures and required parameters have changed
no
=> feat: Upgrade to new V2 Clients and refactor PushToCore

internal/trigger/messagebus/messaging.go, internal/trigger/mqtt/mqtt.go
Only check for JSON format starting with `{`
Issue Number: #894
Add a check for JSON format starting with `[` for arrays.
No
=> fix: Add json array check when determining CBOR of JSON encoding

CHANGELOG.md
Change log not updated for Ireland or Hanoi
Issue Number: #903
Change log now updated for Ireland & hanoi
=> fix: Update ChangeLog for Ireland

CHANGELOG.md
Recent commit missing from change log
Issue Number: /n/a
All commits covered in change log
=> feat: Update final with recent commits

app-service-template/go.mod, go.mod
Using pre-release go-mods
Using released go-mods
=> build: Update to released go-mods

openapi/v2/app-functions-sdk.yaml
V2 Swagger is published with version of 2.x
Issue Number: #915
V2 Swagger is now published with version of 2.0
=> refactor: Change swagger to be published as version 2.0

openapi/v2/app-functions-sdk.yaml
Swagger published to version 2.0
Issue Number:  n/a
Swagger published to version 2.0.0
=> build: change swagger version to 2.0.0

openapi/v2/app-functions-sdk.yaml
Signed-off-by: Cherry Wang <cherry@iotechsys.com>
Issue Number:
Closes #917
=> fix: Change V2 Swagger API version to 2.0.0

pkg/transforms/filter.go, pkg/transforms/filter_test.go
FilterByResource creates copy of Event without all required fields
Unit tests doesn't validate Event is valid after filtering. 
Issue Number: #922
FilterByResource  now creates copy of Event with all required fields
Unit tests now validates Event is valid after filtering.
=> fix: Create Event copy with all required fields

app-service-template/go.mod
Template's go.mod references SDK 2.0.0
Template's go.mod references SDK 2.0.1
no
=> build: Update template go.mod to use SDK 2.0.1

CHANGELOG.md
Change log doesn't have entry for 2.0.1
Change log now has entry for 2.0.1
=> docs: Add 2.0.1 to change log

GOVERNANCE.md, OWNERS.md, app-service-template/res/configuration.toml
Mix of single quotes and double quotes in TOML Files
Replaced single quotes with double quotes in TOML Files
Added governance.md and owner.md files for LF Edge
no
=> refactor: Clean up TOML quotes and add LF MD files

.github/PULL_REQUEST_TEMPLATE.md
PR template does have section for related Docs PR and has obsolete type section
PR template now has section for related Docs PR and no longer has obsolete type section
=> docs: Add related docs PR and cleaned up template

internal/app/service.go, internal/app/service_test.go, internal/app/triggerfactory.go, pkg/interfaces/trigger.go
Allow topic pipeline config for custom triggers & only attempt to use
topic matching method to identify pipelines for execution.
Related Docs PR:
https://github.com/edgexfoundry/edgex-docs/pull/570
If n/a for Docs PR, state why it is not applicable:
Issue Number:
#940
=> fix(sdk): Correct Custom Trigger Pipeline Selection

.github/PULL_REQUEST_TEMPLATE.md
New proposed PR template for shooting darts at.
=> docs: Create new PR template

internal/appfunction/context.go, internal/appfunction/context_test.go, pkg/interfaces/context.go
Offer a clone method on context.
Unit tests sufficient for code not called within SDK
https://github.com/edgexfoundry/edgex-docs/pull/577
=> feat(sdk): Add Clone to Context

app-service-template/Attribution.txt, app-service-template/Makefile
=> ci: Replace references to master with main or version in app-service-template

Makefile
Required changes for Jakarta LTS
=> ci: changes required for Jakara LTS

internal/app/configurable.go, internal/app/configurable_test.go, internal/etm/LICENSE, internal/etm/README.md, internal/etm/etm.go, internal/etm/etm_test.go, pkg/transforms/aesprotection.go, pkg/transforms/aesprotection_test.go, pkg/transforms/encryption.go
Add new transform using AES 256 Encryption with a SHA512 authentication
mechanism.
Fixes #968
unit tests should be sufficient
https://github.com/edgexfoundry/edgex-docs/pull/614
=> feat(transforms): new AES 256 Encryption Transform

pkg/transforms/mqttsecret.go
fixes #318
This allows data to be stored/retried when Store and Forward is enabled
1. Run non-secure Edgex Stack from compose builder using the following command:
```
make run no-secty mqtt-broker
```
2. clone branch for this PR
3. clone app-service-configurable
4. Modify  app-service-configurable go.mod to add following:
```
replace github.com/edgexfoundry/app-functions-sdk-go/v2 => ../app-functions-sdk-go
```
6. Modify app-service-configurable …
=> fix(transforms): MQTTSend should treat connection not open as error.

openapi/v2/app-functions-sdk.yaml
=> docs: Update Swagger version to 2.1.0

internal/app/configupdates.go
fixes #1006
- Run recreate instructions from  #1006.
- Verify now get expected result
N/A
=> fix: Set TargetType properly when dynamically updating to configurable pipeline

openapi/v2/app-functions-sdk.yaml
**N/A to swagger**
**N/A to swagger**
=> docs: Publish swagger to 2.2.0

app-service-template/Dockerfile
Changes related to Go 1.17 and cache optimizations
=> ci: Go 1.17 related changes

app-service-template/Attribution.txt, app-service-template/go.mod, app-service-template/go.sum, openapi/v2/app-functions-sdk.yaml
Add for Ping, Config, Metrics, Version DTOs.
n/a
n/a
=> fix: Missed ServiceName in Swagger

internal/controller/rest/controller.go, internal/controller/rest/controller_test.go
**N/A for unit test fix**
**N/A**
=> fix: Enable controller tests to run and fix failures

app-service-template/Makefile, app-service-template/go.mod, app-service-template/go.sum
fixes:1076
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
=> feat: enable security hardening

app-service-template/res/configuration.toml
Signed-off-by: Anthony Casagrande <anthony.j.casagrande@intel.com>
=> docs: update outdated link in configuration.toml

app-service-template/go.mod, app-service-template/go.sum, go.mod, go.sum, internal/app/configurable.go, internal/app/configurable_test.go, internal/app/service.go, internal/common/config.go, pkg/transforms/metrics.go, pkg/transforms/metrics_test.go
closes #1086
TBD
Use ASC with new profile to test new function and export the data out to InfluxDB
=> feat: Add Line Protocol function to transform Metric DTO

app-service-template/README.md, app-service-template/config/configuration.go, app-service-template/functions/sample.go, app-service-template/main.go, app-service-template/res/configuration.toml
=> fix: Update all doc links in app template to refer to version 2.2

CHANGELOG.md
=> docs: Update change log for Kamakura

openapi/v2/app-functions-sdk.yaml
=> docs: Publish swagger to 2.3.0

internal/trigger/messagebus/messaging.go, internal/trigger/messagebus/messaging_test.go
fixes #1108 for jakarta
no docs change
=> fix: Make deep copy of MessageBus Optional map to avoid external adds

openapi/v2/app-functions-sdk.yaml
=> fix: (Jakarta) Back port swagger /secret fix

internal/trigger/messagebus/messaging.go
Update to MessageBus.
** Logs only
=> fix(triggers): MQTT in MessageBus log

app-service-template/bin/test-attribution-txt.sh
=> build: Optimize test-attribution-txt.sh to use go.mod, not vendor

app-service-template/res/configuration.toml, internal/constant.go, pkg/transforms/mqttsecret.go
applies to #1116
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
1. Run edgex with MQTT broker and device service rest
2. Run app service configurable for mqtt-export with new metric MqttExportSize enabled
3. Run app service configurable for metrics-influxdb to see metrics being published
4. Send message using Postman to send data to the edgex message bus
5. Verify that the log for mqtt-export shows the new metric is registered and published. Verify that the log for metrics-influxdb shows the …
=> feat: add metric to capture mqtt size in bytes

app-service-template/go.mod, app-service-template/res/configuration.toml, internal/app/service.go
=> fix: Revert Client initialization out of MakeItRun

CHANGELOG.md
=> docs: Add recent bug fix to Levski change log

internal/trigger/mqtt/mqtt.go
Signed-off-by: hchw <2012hchw@gmail.com>
It is a refactor for mqtt subscribe, multiple subscription can make the subscription message into one. It can speed up subscription efficiency. Reduce link timeouts caused by long subscriptions.
This scenario can be verified by configuring multiple topics configured in the mqtt trigger. We have verified it in the production environment.
=> refactor: change mqtt connect handler for multiple subscribe

app-service-template/Dockerfile, app-service-template/go.mod, app-service-template/go.sum, go.mod, go.sum
BREAKING CHANGE: renamed `-c/--confdir` to `-cd/--configDir`and `-f/--file` to `-cf/--configFile`
https://github.com/edgexfoundry/edgex-docs/pull/916
Build app template
run `app-new-service  -h`
verify flags in help have new names
run `app-new-service --confdir something`
verify error due to --confdir unknown
run `app-new-service --configDir something`
verify error due to file `something` not found
=> refactor!: Rename command line flags for the sake of consistency

.github/workflows/go.yml, Makefile, app-service-template/Attribution.txt, app-service-template/Dockerfile, app-service-template/Makefile, internal/common/config.go, internal/trigger/messagebus/messaging_test.go
BREAKING CHANGE: ZeroMQ MessageBus capability no longer available
closes #1228
TBD
Run none secure EdgeX Stack
Build template app from this branch 
Verify builds w/o CGO and ZMQ libs
Run template app with Debug logging
Verify run and is receiving data (from Device Virtual)
=> feat!: Remove ZeroMQ MessageBus capability

app-service-template/res/configuration.toml
`cd edgex-compose/compose-builder`
`make run no-secty ds-virtual`
`cd app-functions-sdk/app-service-template`
`make build`
`./app-new-service`
verify that SendGetCommands was successfull
=> fix: add core command client via message bus to app-service-template

app-service-template/Attribution.txt, app-service-template/go.mod, app-service-template/go.sum, go.mod, go.sum, pkg/transforms/tags_test.go
=> refactor: Update to latest core contracts and fix tests

app-service-template/go.mod, app-service-template/go.sum, app-service-template/main.go, go.mod, go.sum, internal/runtime/runtime.go, internal/runtime/runtime_test.go
BREAKING CHANGE: use MQTT wild cards + for single level and # for multiple levels
Signed-off-by: Ginny Guan <ginny@iotechsys.com>
https://github.com/edgexfoundry/edgex-docs/pull/953
1. build and run app service template with other services
2. successfully found two pipeline topics (default and `edgex/events/+/+/Random-Float-Device/#`)
```
level=DEBUG ts=2023-02-06T16:00:40.363421Z app=app-new-service source=messaging.go:175 msg="MessageBus Trigger: Received message with 495 bytes on topic …
```
=> refactor!: Update message bus topic wild cards

app-service-template/res/configuration.yaml
1. Startup edgeX with no-secty
2. Build app-service-template
3. Uncomment localhost hybrid settings
4. Startup app-service-template using -cp flag and -cp -o flag
5.  Verify that there are no issues
=> fix: Add localhost settings to configuration for hybrid mode

app-service-template/Attribution.txt, app-service-template/go.mod, app-service-template/go.sum, go.mod, go.sum
=> build: Update to latest modules w/o TOML package

app-service-template/Dockerfile, app-service-template/config/configuration.go, app-service-template/functions/sample.go
=> fix: Rename toml references in comments to yaml

Jenkinsfile, pkg/transforms/compression.go
=> fix: [jakarta] Make Compression functions thread safe

CHANGELOG.md
=> docs: [Jakarta] Update Changelog for 2.1.2 patch

pkg/transforms/compression.go
- [X ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
=> fix: [Levski] Make Compression functions thread safe

CHANGELOG.md
=> docs: [Levski] Update change log for patch release

pkg/transforms/compression.go, pkg/transforms/compression_test.go
https://github.com/edgexfoundry/app-functions-sdk-go/pull/1375 was merged to fix data race issue reported on https://github.com/edgexfoundry/app-functions-sdk-go/issues/1250.  The fix is to instantiate new writer each time when new data is passed into `CompressWithGZIP` or `CompressWithZLIB`.  Another way to avoid the data race is to use mutex to ensure atomic gzip/zlib writer operation.
After test, using mutex has much better benchmark number than the number of using local writer (both running against https://github.com/edgexfoundry/app-functions-sdk-go/blob/main/pkg/transforms/compression_test.go).  This commit changes the implementation of Compression functions to use mutex instead.
fixes #1384
**If your build fails**  due to your commit message not passing the build checks, please …
=> refactor: Make Compression functions thread safe

.github/dependabot.yml
=> build: Ignore all go-mod deps, except go-mod-bootstrap

app-service-template/Attribution.txt
=> refactor: Remove github.com/pkg/errors from Attribution.txt

README.md
Click repo links in rendered README
Verify they open the correct section in the latest EdgeX Docs
=> docs: Update repo links to point to latest docs

Makefile, app-service-template/Dockerfile, app-service-template/go.mod, app-service-template/go.sum, go.mod
=> build: Upgrade to go-1.21, Linter1.54.2 and Alpine 3.18

app-service-template/go.mod, app-service-template/go.sum, go.mod, go.sum, internal/app/service_test.go, internal/appfunction/context_test.go
=> build: Update to latest go-mod-bootstrap, fix unit tests

internal/app/configupdates.go
fixes #1541, #1540
run test from #1541 
Verify message is now
```
msg="No configuration changes detected that need special processing"
```
Make changes to pipeline configuration
Verify logs contain
```
msg="Configurable Pipeline successfully reloaded from new configuration"
```
=> fix: Properly detect config changes so pipeline is rebuilt only when it changes

app-service-template/Attribution.txt
=> docs: Add missing package to Attribution.txt

pkg/transforms/mqttsecret.go
feature for https://github.com/edgexfoundry/edgex-examples/issues/241
=> feat: set MQTT client OnConnect before connect to broker

app-service-template/Makefile
Run the following command to build binary
```
make build
```
Verify that `Full RELRO` and `PIE enabled` are displayed
```
checksec --file=./app-service-template/app-new-service
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      No canary found   NX enabled    PIE enabled     No RPATH   No RUNPATH   59296) Symbols	  No	0		0		./app-service-template/app-new-service
```
=> feat: Enable PIE support for ASLR and full RELRO

Jenkinsfile, openapi/README.md, openapi/app-functions-sdk.yaml
https://github.com/edgexfoundry/edgex-go/issues/4978
=> fix: Move API document files from openapi/v3 to openapi

pkg/transforms/filter.go, pkg/transforms/filter_test.go
=> fix: Fix missing tags issue in FilterByResourceName func

internal/app/configupdates.go, internal/app/service.go, internal/app/service_test.go, internal/app/storeforward.go, internal/common/config.go, internal/runtime/storeforward.go
=> fix: add lock for Writable to avoid race conditions

.github/dependabot.yml
=> build: Ignore sub-dependency from dependabot

app-service-template/go.mod, app-service-template/go.sum, go.mod, go.sum
=> build: update to release bootstrap 4.0.2

.gitignore, app-service-template/.gitignore, app-service-template/Attribution.txt, app-service-template/vendor/github.com/go-openapi/analysis/internal/debug/debug.go, vendor/github.com/go-openapi/analysis/internal/debug/debug.go
Also add missing semver into Attribution.txt
=> build: update gitignore to avoid ignore debug pkg
