edgexfoundry/app-functions-sdk-go

appsdk/sdk.go
examples/simple-filter-xml-mqtt/main.go
pkg/transforms/mqtt.go
pkg/transforms/mqtt_test.go

This is a first Idea how to use additional parameter in mqtt export.Qos , retain and autoconnect are imho something you can customize from an sdk point of view.
Actually  I don't like very much the implementation that uses parameters in MQTTSend() func : maybe is a good idea to use a struct but we must export the type somewhere.
thanks for comments
Marco

first implementation with an mqtt configuration for Qos, Retain and Autoreconnect.

---

appcontext/context.go
go.mod
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/trigger/messagebus/messaging_test.go

This PR addresses #59 and also saves the EventId or EventChecksum in context for later use when marking event as handled.

Add support for CBOR encoded events

---

internal/runtime/runtime.go
internal/trigger/http/rest.go

PR address #59 for rest trigger
Also found defect/fixed defect in previous CBOR PR #73

Added CBOR support to rest trigger and fixed CBOR defect

---

appcontext/context.go
appsdk/sdk.go
appsdk/sdk_test.go
examples/advanced-filter-convert-publish/res/configuration.toml
examples/advanced-filter-convert-publish/res/docker/configuration.toml
examples/simple-filter-xml-mqtt/res/configuration.toml
examples/simple-filter-xml-mqtt/res/docker/configuration.toml
examples/simple-filter-xml-post/res/configuration.toml
examples/simple-filter-xml-post/res/docker/configuration.toml
examples/simple-filter-xml/res/configuration.toml
examples/simple-filter-xml/res/docker/configuration.toml
go.mod
internal/common/config.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/trigger/http/rest.go
internal/trigger/messagebus/messaging.go
internal/webserver/server_test.go
pkg/startup/endpoint.go
pkg/transforms/conversion_test.go
pkg/transforms/filter_test.go
pkg/transforms/http.go
pkg/transforms/http_test.go
pkg/transforms/mqtt.go
pkg/transforms/mqtt_test.go

This pull request provides a function on the context that allows developers to optionally mark an event as pushed in core data once it has been sent to the desired destination. It will also mark events as pushed if using the SDK provided HTTP/MQTT export functions. An error will be logged if the mark fails; However, it will not stop the pipeline in the event of failure.

Mark as pushed

---

appsdk/sdk.go
examples/advanced-filter-convert-publish/main.go
examples/simple-filter-xml-mqtt/main.go
examples/simple-filter-xml-post/main.go
examples/simple-filter-xml/main.go

This PR addresses issue #83 
SDK no longer calls os.exit and leaves it to the caller to exit properly after doing any potential clean-up.

Changed SDK to never exit so caller can do clean-up

---

README.md
examples/advanced-filter-convert-publish/README.md
examples/simple-cbor-filter/main.go
examples/simple-filter-xml-mqtt/main.go
examples/simple-filter-xml-post/main.go
examples/simple-filter-xml/EdgeX Application Function SDK Device Name.postman_collection.json
examples/simple-filter-xml/EdgeX Applications Function SDK.postman_collection.json
examples/simple-filter-xml/main.go

This PR addresses #97 .
Updates for device name changed to `Random-Float-Device`
Updated advanced example ReadMe to change Device Virtual device profile to use expected floatEncoding and to set min/max values

Updated examples for changes to Device Virtual

---

internal/runtime/runtime.go
internal/trigger/messagebus/messaging.go

This PR addresses #99 
Simply set the Evnvelope.ContentType before publishing.
Also fixed typo in error message when content type wasn't set.

Fix bug where ContentType isn't set when publishing back to bus

---

Dockerfile.build
Dockerfile.build-arm64
Jenkinsfile

Hold while testing on the sandbox
Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>

build: Add pipeline build

---

appsdk/sdk.go
go.mod
internal/common/loader.go
internal/config/environment.go
internal/config/environment_test.go

Added ability to override configuration.toml-provided registry address
with environment variables -- edgex_registry_host, edgex_registry_port,
and edgex_registry_type to be consistent with edgex-go core implementation
(see https://github.com/edgexfoundry/edgex-go/issues/1450).
Added ability to override any configuration value with environment
variables for the use case where a command line registry flag is
provided, the referenced registry does not have configuration for this
service, and this service pushes a copy of its local configuration into
the registry. The key in an environment variable specifies the
configuration value to override; e.g. Clients_Logging_Host=<someNewValue>
https://github.com/edgexfoundry/app-functions-sdk-go/issues/134
Signed-off-by: Michael W. Estrin …

feat(env-variables): Override Configuration Using Environment Variables

---

appsdk/sdk.go
appsdk/sdk_test.go
internal/common/config.go
internal/common/loader.go

This addresses #147 by Marshaling the configuration object to TOML tree just before needing to push into Consul. Empty Pipeline.Functions nodes in the TOML file end up with an empty Addressable in Consul allowing them to exist in Consul.

bugfix(empty TOML Node): Allow for empty TOML nodes used in Pipeline configuration

---

README.md
pkg/transforms/filter.go
pkg/transforms/filter_test.go

Filter functions allow all events/reading to pass through (unfiltered) when the list of filter values is empty, rather then filter out all events/readings. This allows filter functions to be in the pipeline via configuration, but not filter if no filter values set until the values are dynamically updated via Consul.
Closes #137 

feat(Filter): Pass all events/reading through if no filter values are set

---

examples/simple-filter-xml/main.go
go.mod
internal/constants.go
internal/webserver/server.go
internal/webserver/server_test.go
makefile

This endpoint will provide both version of the SDK that is in use as well as the version of the application service. These version values are intended to be set at build time leveraging -ldflags.
closes #152

feature(version): Add /api/version endpoint to SDK

---

README.md
appsdk/sdk.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
pkg/transforms/encryption.go
pkg/transforms/encryption_test.go
pkg/transforms/filter.go
pkg/transforms/filter_test.go

Allow the Target Type for the incoming data to be specified by developer. This allows data other than Events to be processed be the function pipeline.
closes #79

feat(runtime): Support types other than Event to be sent to function pipeline

---

appsdk/configurable.go
examples/simple-filter-xml-mqtt/main.go
pkg/transforms/mqtt.go
pkg/transforms/mqtt_test.go

This is to address issue #157 adding support to allow to pass MQTT key/pair as byte array so that the client can retrieve cert/key from some more secure sources like vault before the SDK supports it.
Signed-off-by: David Chang <david@iotechsys.com>

Support to pass MQTT key/pair as byte array

---

README.md
appsdk/sdk.go
internal/config/environment.go
internal/config/environment_test.go

Added special case environment variable override of the Service connection information before the service registers with the Registry.
close #172

feat(configuration) Environment variable override of the Service connection information

---

README.md
appsdk/sdk.go
appsdk/sdk_test.go
internal/common/config.go
internal/webserver/server_test.go

With the addition of the UseTargetTypeOfByteArray boolean setting the functions pipeline can be configured to accept a byte array as input to the first function in the pipeline. This is instead of the default EdgeX Event object. Having this setting in the Writable Pipeline section allows it to be changed appropriately to match the first function in the pipeline as it is changed.
closes #177

feat(configuration) : Add UseTargetTypeOfByteArray to Pipeline confguration

---

README.md

This fixes the unknown type error In the example code in the README for the `printToXML()` function.
closes #169

docs(readme): Address unknown type issue from getting started section

---

appsdk/sdk.go

Check interval was previously hardcoded to 1s. It is now determined by configuration.
closes #182

fix(configuration): Check Interval is now respected

---

internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/trigger/http/rest.go
internal/trigger/messagebus/messaging.go
internal/trigger/messagebus/messaging_test.go

Any error during message processing or from pipeline functions should cause an error response from the HTTP trigger.
closes #174

fix(trigger): Return error to HTTP trigger response

---

go.mod
internal/runtime/runtime.go

Must make a copy of the target type so that data isn't retained between calls.
closes #189

fix(TargetType): Make copy of target type before using it.

---

README.md
appcontext/context.go
appcontext/context_test.go
appsdk/sdk.go
appsdk/sdk_test.go
internal/common/clients.go
internal/trigger/http/rest.go
internal/trigger/messagebus/messaging.go
internal/trigger/messagebus/messaging_test.go
internal/trigger/trigger.go

Add ValueDescriptorClient, CommandClient and NotificationsClient to context for functions to use.
EventClient already exist on the context.
closes #124

feat(Context): Add useful edgex clients to expose them for pipeline functions and internal use

---

appsdk/sdk.go
go.mod

Must use clients.ApiDeviceRoute, not clients.ApiCommandRoute for Command Client to send commands.
Closes #219

bug(CommandClient): Use proper API Route for Command Client

---

README.md
appsdk/sdk.go

When running app-service-configurable or any service as a snap service changing the command line options is not possible. Thus the need to add an environment override for specifying the profile.
Addresses https://github.com/edgexfoundry/app-service-configurable/issues/22
Updating app-service-configurable to use latest SDk will close the issue.

feat(profile): Add environment override for profile command line argument

---

README.md
appsdk/configurable.go
examples/simple-filter-xml-mqtt/main.go
pkg/transforms/mqtt.go
pkg/transforms/mqtt_test.go

Replace hard coding skip verify to `true` with a setting in MqqtConfig struct. Also enable this to be set via the configurable functions pipeline.
Refactor MqttSend code to be more in align with rest of SDK's code
Skip Verify is hard coded to `true`
Issue Number: #233
Capability to set Skip Verify from code or from pipeline configuration.

feat(MqttSend): Add SkipCertVerify setting and refactor MqttSend

---

README.md
appsdk/sdk.go
appsdk/sdk_test.go
internal/constants.go

Issue Number: #151 
Validates that the SDK's major version matches Core Service's major version.
Includes a -i/--ignoreVersion command-line option to override version check errors.
SDK version starting with "0" is always valid as it is either a Beta Version or being run in the debugger.

feat(version): Validate that SDK's major version matches Core Service's major version

---

README.md
appsdk/sdk.go

SDK pushes local settings into Registry only if the root key doesn't exist in the Registry
Issue Number: #176
Added -o/--overwrite command-line option to overwrite configuration in Registry with local settings rather than loading the settings from the Registry.

feat(configuration): Add overwrite option for force local settings into Registry

---

README.md
appsdk/sdk.go
appsdk/sdk_test.go

All app services will have comma separated list of names in their ApplicationSettings for `device names` or `value descriptors` and need to pares them into string slice for filtering. Each service must repeat the code for this parsing.
Issue Number: #267
SDK now has helper function to retrieve and parse app settings that are comma separated strings.

feat(sdk): Add helper function to SDK to get string slice from App Settings.

---

appsdk/sdk.go
go.mod
internal/security/client/testdata/expiredToken.json
internal/security/client/testdata/replacement.json
internal/security/client/testdata/testToken.json
internal/security/client/vaultclient.go
internal/security/client/vaultclient_test.go
internal/security/mock/mockserver.go
internal/security/secret.go
internal/security/secret_test.go

Refactor and update the usage of NewSecretClient into its own package client Vault to be able to use the latest NewSecretClient constructor with NewSecretClientFactory
- unit tests and related test data added for refactor and updates
- a mock server is added into its own package to facilitate unit testings on both vaultclient_test and secret_test
- update go.mod to use go-mod-secrets version **v0.0.15**
Lots of testing related code added with minimal code changes and implementation.
Fixes issue #277
The signature of `NewSecretClient()` of go-mod-secrets from older version (v0.0.14 and below) has been changed in version **v0.0.15**. …

refact(sdk): Update usage of NewSecretClient to use the latest go-mod-secrets

---

README.md
appsdk/sdk.go
appsdk/sdk_test.go
internal/security/credentials.go
internal/security/credentials_test.go
internal/security/secret.go
internal/security/secret_test.go
internal/webserver/server.go
internal/webserver/server_test.go
internal/webserver/types.go

There is currently no way to push secrets via an app function. 
Issue Number: [269](https://github.com/edgexfoundry/app-functions-sdk-go/issues/269)
Now users can use the secret client to push secrets into Vault.  The secrets pushed in are only available to the app function that pushed them in.
Also included is a slight change to the 'AddRoute' function definition now this function returns an error as opposed before when the error messages were suppressed.

Implement StoreSecrets endpoint in app functions SDK

---

README.md
internal/constants.go
internal/webserver/server.go
internal/webserver/server_test.go

This pr adds the full path to the route and updates the unit tests accordingly.
closes #294
Signed-off-by: adam-w-mitchell <adam.w.mitchell@intel.com>
Currently, the api route is simply /secrets it should be /api/v1/secrets
Issue Number: 294
Fixes the route on secrets api

feat(sdk): Add full path to secrets api route

---

appsdk/sdk_test.go
internal/config/environment_test.go
internal/runtime/runtime_test.go
internal/runtime/storeforward_test.go
internal/security/authtokenloader/methods_test.go
internal/security/credentials_test.go
internal/security/fileioperformer/methods_test.go
internal/store/db/mongo/models/storedobject_test.go
internal/store/db/mongo/store_test.go
internal/store/db/redis/store_test.go
internal/trigger/messagebus/messaging_test.go
pkg/transforms/compression_test.go
pkg/transforms/conversion_test.go
pkg/transforms/filter_test.go
pkg/transforms/http_test.go
pkg/transforms/mqtt_test.go
pkg/transforms/outputdata_test.go
pkg/util/helpers_test.go

Many tests using assert.Equal() have the expected & actual parameters swapped.
Many tests use the follow pattern to fail fatal:
```
if !assert.(..) {
t.Fatal()
}
```
Many tests use assert.Nil() to check validate errors
Issue Number: #286 
assert.Equal() parameter order correct
require.() used instead of conditional to fail fatal
require.NoError()/require.Error() used to validate errors and fail fatal
None

refactor(tests): Fix order of expected vs actual and other clean up

---

go.mod

Wrong version of ZMQ package specified in go.mod which breaks build in Windows
Issue Number: #306
Removed ZMQ package from go.mod as it is a indirect dependency from go-mod-messaging and doesn't need to be specified.

fix(go.mod): Removed wrong version of ZMQ package used.

---

README.md
appsdk/sdk_test.go
internal/security/credentials.go
internal/security/credentials_test.go
internal/security/secret.go
internal/webserver/server_test.go
pkg/transforms/conversion_test.go
pkg/transforms/http.go
pkg/transforms/http_test.go

Enables retrieval of secret value for use in header in HTTP Export.
Closes #278
Co-authored-by: Walt <walter.a.morton@intel.com>
Co-authored-by: adam-intel <adam.w.mitchell@intel.com>
Authentication Header is added to HTTP Post method using key provided from /path in secret provider .

feat(http-export): add support for auth token in header

---

README.md
internal/common/config.go
internal/security/credentials.go
internal/security/credentials_test.go
internal/security/secret.go
internal/webserver/server.go
pkg/transforms/http_test.go

SecretProvider now has an exclusive secret client for retrieving per-service secrets
Closes: #275
Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>
Issue Number:

feat(security): Add second SecurityStore client for service specific secrets

---

internal/security/credentials.go
internal/security/credentials_test.go
internal/security/secret.go
internal/security/secret_test.go

This is to fix bug #315: SecretStore clients should only be created is configured.
- Creation of each of the SecretStore clients is skipped if not configured.
- The creation is a per SecretStore client decision since the exclusive client may be configured
when the shared client isn't configured.
- Add some more test entries on the existing TestInitializeSecretProvider for optional secret stores.
- Refactor some unit tests to avoid potential threading errors on the existing unit tests.
Fixes: #315
Currently, if SecretStore section is not provided in the congfiguration TOML file, then the application service throws error and stops …

fix(SecurityProvider): Make initialization of secret clients optional

---

go.mod
internal/security/credentials.go

Empty credentials always returned for Redis
Issue Number: #340
Also addresses https://github.com/edgexfoundry/go-mod-bootstrap/issues/72 by using latest go-mod-bootstrap
Credentials from Secret Store (Vault or InsecureSecrets) are returned for Redis

fix: Remove code that returns empty credentials for Redis

---

internal/security/credentials.go

Error on startup if DB credentials not in `[InsecureSecrests]`
Issue Number: #343
Credentials from `[Database]` config are used if not found in `[InsecureSecrets]`
This fixes backwards breaking change

fix: Use credentials from Database config if not found in InsecureSecrets

---

pkg/transforms/jsonlogic.go

closes #346
- [x Bugfix
JSONLogic rule executes once
JSONLogic rule executes as its supposed to

fix: JSONLogic now runs rules everytime insted of 1st time

---

appsdk/configurable.go

Receive `none not found ` error on startup of app-service-configurable with MQTTSecretSend in the pipeline execution order.
Issue Number: #357
No error and able to connect to secure MQTT broker with Authmode set to `usernamepassword`

fix: Use correct parameter key name for MQTTSecretSend AuthMode in configurable pipeline

---

README.md
appsdk/sdk.go
appsdk/sdk_test.go

No support for for overriding the service key
Issue Number: #355
have ability for command-line and environment override of service key
Command line options are -sk/--serviceKey
Environment varable is EDGEX_SERVICE_KEY
Includes support for the <profile> replacement text placeholder
- [] No
Inserting preceding "-" when replacing `<profile>` in the service key has been removed so the use is more flexible.  The only service using the <profile> replacement text is app-service-configurable which will be updated to add the "-" in the initial service key

feat: Add ability for command-line and environment override of service name

---

README.md
appsdk/sdk.go
appsdk/sdk_test.go

Currently overrides are named ` -n/--serviceName & EDGEX_SERVICE_NAME`
Issue Number: #363
Now overrides are named `-sk/--serviceKey & EDGEX_SERVICE_KEY`

refactor: Change serviceName override to be ServiceKey

---

go.mod

Env overrides with blank values such as Service_Host="" were ignored.
Issue Number: #373
Updated to use v0.0.32 of go-mod-bootstrap
Env overrides with blank values now work.

fix: Allow overrides that have empty/blank value

---

internal/bootstrap/handlers/clients.go

Signed-off-by: charles-knox-intel <44684517+charles-knox-intel@users.noreply.github.com>
The `ctrl+C` interrupt signal from the keyboard is not being correctly handled in downstream app services. 
Issue Number: https://github.com/edgexfoundry/app-service-configurable/issues/74
The proper `context` is now being passed to clients during app services bootstrap, which in turn allows the interrupt signal event to be handled by downstream client handlers.
No
Downstream repositories will need to be updated in order to receive this bugfix.
N/A

fix: app-service-configurable issue 74

---

internal/common/config.go
internal/webserver/server.go

Signed-off-by: charles-knox-intel <44684517+charles-knox-intel@users.noreply.github.com>
The `ListenAndServe` internal API calls to start the app functions SDK web server currently only listen on `:<port>`, which prevents developers from using the SDK in various environments that may not allow for binding on the `0.0.0.0` interface.
Issue Number: #405 
A new configurable option called `ServerBindAddr` has been added, similar to https://github.com/edgexfoundry/go-mod-bootstrap/pull/84 and https://github.com/edgexfoundry/go-mod-bootstrap/issues/83. If `ServerBindAddr` is not specified, `app-functions-sdk-go` will instead use the `Host` value from the service's configuration. If neither …

feat: configurable ListenAndServe address, fixes #405

---

internal/webserver/server.go

Signed-off-by: charles-knox-intel <44684517+charles-knox-intel@users.noreply.github.com>
When setting `ServerBindAddr` (newly introduced in #406), setting a blank value causes `app-functions-sdk-go` to default to the `Service.Host` value instead. This is actually not a backwards-compatible change.
Issue Number: #408 
The new behavior is intended to actually be backwards-compatible this time. If `ServerBindAddr` is set to blank value, then the value that is sent to `ListenAndServe` is `:<port>`. This is the previous behavior of `app-functions-sdk-go`.
No
No

fix: backwards compatibility broken by #406, fixes #408

---

internal/bootstrap/handlers/version.go
internal/bootstrap/handlers/version_test.go

Version check expects `master` for Core Data's `dev` version
Issue Number:  #100
Core Data is now using the semver tag, e.g. `1.2.1-dev.1` , for it's `dev` version.
Version check update to handle new Core Data `dev` version format
no

fix(sdk): Fix version check to handle new core-data `dev` versions.

---

appsdk/sdk.go

fixes: #423
Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>
The service startup message is currently logged using the message bootstrap handler during the SDK initialize(). This occurs too early as the SDK does additional processing after the bootstrap handlers run. 
Issue Number:
#423 
Remove use of message bootstrap handler and just need to log the same messages after the call to the SDK Initialize() completes.
No
No

feat: Add logging of service version and total startup time

---

internal/v2/controller/http/controller.go
internal/v2/controller/http/controller_test.go
openapi/v2/app-functions-sdk.yml

V2 Secrets returns 207 for the HTTP Response and then has the appropriate status code in the BaseResponse object returned in the body.
207 in meant for when there are multiple responses in the body for multiple requests in the request body, which is not the case here. 
Issue Number: #442
Returns the appropriate 201, 400, or 500 status code as the HTTP response and also in the BaseResponse object in the response body
No

fix: V2 Secrets return proper 201, 400 or 500 status codes, not 207.

---

openapi/v2/app-functions-sdk.yml

Swagger for the Trigger API sets the schema type to `text for the error responses. `text is not a valid type.
Issue Number:  #452
type has been changed to the valid type of `string`
no

fix: Trigger API schema type of `text` for errors is invalid, should be `string`

---

appsdk/backgroundpublisher.go
appsdk/backgroundpublisher_test.go
appsdk/sdk.go
appsdk/sdk_test.go
internal/trigger/http/rest.go
internal/trigger/http/rest_test.go
internal/trigger/messagebus/messaging.go
internal/trigger/messagebus/messaging_test.go

Creates a channel of provided capacity and attaches to the sdk instance.
This channel is then passed to the trigger so that MessageEnvelopes can
be pulled off of it and dropped on the queue.  Publisher handles
formatting the passed message so there is no need to couple using types
from go-mod-messaging.
Closes: #462
Issue Number: 462
Adds a background publisher for MessageBus services
No

feat(sdk): Add background publisher to MessageBus

---

internal/v2/controller/http/controller_test.go
internal/v2/dtos/requests/secrets.go
internal/v2/dtos/requests/secrets_test.go
internal/webserver/server_test.go
internal/webserver/types.go

Secrets API (V1 & V2) `path` property is currently optional, but results in error from Vault due to not having write privs for the base path.
Issue Number:  #476
`path` property is now required for both V1 & V2 Secrets API.
For V1 it results in a n error, so no one could have successfully used Secrets API w/o path set
No

fix: Make `path` property required for the Secrets V1 & V2 APIs

---

appsdk/sdk.go

make internal client used for registry communications available to
the service after initialization
Expose the registry client on initialized SDK for use by application services
Registry client on SDK is not exposed
Issue Number: #502
Registry client on SDK is exposed
No
No

feat(sdk): expose RegistryClient on SDK

---

internal/bootstrap/handlers/version.go
internal/bootstrap/handlers/version_test.go

Version compatibility check will fail when core data's version is 0.0.0. This is the version assigned when built locally by developers.
Issue Number: #532
Version compatibility check is skipped when core data's version is 0.0.0.
No

fix: Skip compatibility check when Core Data's version is 0.0.0 (developer build)

---

appsdk/sdk.go
go.mod

Unable to connect to Redis for redisstreams in secure mode since the random generated Redis password never passed in the MessageBus.Optional properties.
Issue Number: #530
Now the Password is extracted from the SecretProvider and set in MessageBus.Optional properties when `redisstreams` is used.
no

fix: Set Redis password in MessageBus.Optional when using redisstreams

---

appcontext/context.go
appsdk/configurable.go
appsdk/configurable_test.go
internal/trigger/http/rest.go
pkg/transforms/conversion.go
pkg/transforms/conversion_test.go
pkg/transforms/outputdata.go

If content-type is set on the context, the http trigger will use it
and set the appropriate header value on the response.
closes: #512
Signed-off-by: = Beau Frusetta <beau.frusetta@intel.com>
HTTP trigger does not set the response content-type
Issue Number: #512 
Response content-type is now available on context and if set, it will be included in response headers. We also added the OutputDataWithContentType to use with app-service-configurable.
No new packages

fix: http trigger response can set content-type

---

pkg/transforms/compression.go
pkg/transforms/compression_test.go
pkg/transforms/encryption.go
pkg/transforms/encryption_test.go

When chaining TransformToJSON and CompressToGZip, the content type by default sets to application/json.
Issue Number:
#567 
SetOutputData will return an appropriate content-type header based on the chained transforms.
no

fix: Fix response content type issue 567

---

appsdk/sdk.go
appsdk/sdk_test.go

Store reference on the sdk to a CancelFunc created in MakeItRun and
expose to enable clean programmatic exits.
Currently there is no way to exit the service programmatically.
Issue Number:
#612 
Adds a MakeItStop method to the sdk instance that allows calling a cancel function managed by MakeItRun.
No
No

feat(sdk): Add MakeItStop

---

appcontext/context.go
appcontext/context_test.go
go.mod
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/trigger/messagebus/messaging_test.go
pkg/transforms/conversion.go
pkg/transforms/conversion_test.go
pkg/transforms/filter.go
pkg/transforms/filter_test.go
pkg/transforms/outputdata_test.go
pkg/transforms/tags.go
pkg/transforms/tags_test.go
pkg/util/helpers_test.go

Triggers and some pipeline function expect a V1 Event model
Issue Number: #595
Triggers and appropriate pipeline functions now expect a V2 Event DTO.
V1 Event model temporarily supported by converting V1 Event to a V2 Event DTO.
no

feat: Expect V2 Event DTO from triggers.

---

go.mod

Previous version of go-mod-messaging used older version of ZMQ module that has system call interrupt bug.
https://github.com/edgexfoundry/go-mod-messaging/issues/76
Issue Number:  #652
Hanoi branch now uses go-mod-messaging that uses new version of ZQM module that has fix the bug
no

fix: Upgrade to go-mod-messaging with ZMQ fix for Hanoi 

---

internal/runtime/runtime.go

No logging of Event details when recieved
Issue Number: #665
Now event details are logged as Debug messages
no

feat: Add debug logging of Event/Reading details

---

appsdk/configurable.go
pkg/transforms/filter.go

FilterByProfileName debug messages display DeviceName instead of ProfileName
FilterByResourceName debug messages are repeated due to the loop logic.
In general the debug messages need to be enhance to be more useful.
Issue Number: #685
FilterByProfileName debug messages correctly display ProfileName
FilterByResourceName debug messages are no longer repeated due to the loop logic
Enhanced the debug messages to provide better details of what is accept/not accepted by the filters
no

fix: Fixed and enhanced Filter function debug messages

---

appsdk/triggerfactory.go
appsdk/triggerfactory_test.go

Was panicing on errors encountered in custom trigger creation, makes
more sense to force returning and let sdk handle it.
Issue Number:
#698 
Consistently return nil trigger to the SDK.

fix(sdk): Normalize Trigger Factory Returns

---

appsdk/configupdates.go
appsdk/sdk.go
appsdk/sdk_test.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go

Error building from configuration leaves previous pipeline in tact and allows it to execute which hides the error that occurred.
Issue Number: #707
Pipeline now is reset to empty when error building from configuration so that an error is generated each time it is executed.
no

fix: Errors in dynamic pipeline updates allow previous pipeline to run, hiding the errors

---

appsdk/configurable.go
appsdk/configurable_test.go
pkg/transforms/http.go
pkg/transforms/http_test.go

SecretHeaderName used as key for InsecureSecrets is dynamic so can not be overridden in the 'http-export' profile which just has a place holder.
Issue Number: #521
Now the key in InsecureSecrets can be fixed in the 'http-export' profile since is is not also used as the HTTP Header Name.
This allows for the header value stored in InsecureSecrets to be overridden with environment variable.
BREAKING CHANGE: Parameters have changed for HTTP Post/Put with SecretHeader
no

refactor: Rework secrets for HTTP Export so value in InsecureSecrets can be overridden

---

internal/appfunction/context.go
internal/bootstrap/handlers/clients.go
internal/bootstrap/handlers/clients_test.go
internal/bootstrap/handlers/version.go
internal/bootstrap/handlers/version_test.go

Clients configuration uses arbitrary names that have be standardized somewhat across edgex services.
Issue Number: #739
Clients configuration now uses the services service key for the names which are standard across all services.
BREAKING CHANGE: Clients configuration has changed and must be updated to use service keys for names
no

refactor: Change to using service keys for names in Clients configuration

---

internal/app/service.go
internal/app/service_test.go
pkg/interfaces/mocks/AppFunctionContext.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go

GetAppSetting() convenience API doesn't exist so devs have to deal with ApplicationSetting string map directly
Issue Number: #760
GetAppSetting() convenience API exists making it much easier for devs to pull a setting value out of the ApplicationSetting config section
no

feat: Add GetAppSetting() convenience API

---

internal/app/triggerfactory.go
pkg/interfaces/trigger.go

Expose appService.LoadCustomConfig to triggers so that they can load
custom trigger-specific configuration (from root level of config file
only)
#763 
Passes appService.LoadCustomConfig on in triggerConfig.ConfigLoader
The only breaking change is the removal of MessageBusConfig from the TriggerConfig type - since this was introduced in v2 to replace the old full configuration, I may have been the only person using it :)
No

refactor(v2): Update Custom Trigger Configuration

---

app-service-template/res/configuration.toml
go.mod
internal/webserver/server.go

If `If `ServerBindAddr ` is blank, webserver listens to any interface rather than locked down to value of Host as with all other EdgeX services.
` is blank, webserver listens to any interface rather than locked down to value of Host as with all other EdgeX services.
Issue Number: #775
If `ServerBindAddr ` is blank, webserver listens to value of Host as with all other EdgeX services.
BREAKING CHANGE: Webserver will be locked down to listen just to `Host` value when If `ServerBindAddr ` is blank
no

fix: Fix webserver to use ServerBindAddr only if not blank as rest of EdgeX

---

app-service-template/go.mod
app-service-template/res/configuration.toml
go.mod
internal/app/service.go
internal/common/config.go

Currently expecting the Registry/Config Access tokens to be retrieved for files using the file location config settings.
Issue Number: #769
Now uses SecretProvider to retrieve the access tokens.
File location config settings have been removed
BREAKING CHANGE: All App Services running with the secure Edgex Stack now need to have the SecretStore configured, a Vault token created and run with EDGEX_SECURITY_SECRET_STORE=true.
no

refactor: Replace file based with use of Secret Provider to get Access Tokens

---

app-service-template/go.mod
app-service-template/res/configuration.toml

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.
ZMQ is the default MessageBus
Redis is now the default MessageBus
BREAKING CHANGE: All service sending Events must now be configured to use Redis as the MessageBus
Are there any specific instructions or things that should be known prior to reviewing?

feat: Switch to Redis as the default MessageBus for template service

---

Makefile
app-service-template/go.mod
app-service-template/res/configuration.toml
go.mod

**Dependent on edgexfoundry/go-mod-core-contracts#613
Dependent on edgexfoundry/go-mod-bootstrap#216**
Service key constants have the edgex- prefix
Issue Number: #801 & #837
Service key constants no longer have the edgex- prefix
Hyphen in Overrides are converted to underscore
BREAKING CHANGE: Service key names used in configuration have changed.
no

refactor: Update for new service key names and overrides for hyphen to underscore

---

app-service-template/go.mod
go.mod
internal/app/service.go
internal/appfunction/context.go
internal/appfunction/context_test.go
internal/bootstrap/container/clients.go
internal/bootstrap/handlers/clients.go
pkg/interfaces/context.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go

Register v2 client in dic and change interface used throughout.
v1 client is still exposed to custom services by the SDK, does not work with commands routed to v2 device services.
Issue Number: #844
v2 client is registered with dic and interface used in references throughout.
Yes this will break any usages of the client retrieved through context.CommandClient() by returning a new interface.
I updated the mocks by hand since I didn't want to worry about mockery version or usage differences messing something up.

feat(sdk): Use v2 Command Client

---

internal/trigger/mqtt/mqtt.go

Pass context.ResponseData function result instead of reference to paho
client
passes reference to the ResponseData function to paho client instead of response data itself.
Issue Number: #848

fix(sdk): External MQTT Trigger Publish

---

internal/app/configurable.go
internal/app/configurable_test.go
pkg/transforms/mqttsecret.go

KeepAlive and ConnectTimeout MQQ setting for MQTT Export not available
Issue Number: #858
KeepAlive and ConnectTimeout MQQ setting no part of MQTT Export

feat: Add KeepAlive and ConnectionTimeout to MQTT Export settings

---

app-service-template/res/configuration.toml
go.mod

`SecretStore` config no longer support Retry related properties and secret path now only needs service specific path, `/v1/secret/edgex/` automatically prefix in front of it.
Fixes: #864
- [x ] Refactoring (no functional changes, no api changes)
Retry related properties in toml file and secret path is still full path.
Issue Number: #864 
Retry related properties are removed and secret path now only contains the service specific path.
- [x ] No

fix: Clean up retry properties and update secret path

---

internal/appfunction/context.go
internal/appfunction/context_test.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/runtime/storeforward.go
internal/runtime/storeforward_test.go
internal/store/contracts/storedobject.go
internal/store/db/redis/models/storedobject.go
internal/store/db/redis/models/storedobject_test.go
pkg/interfaces/context.go

Add a map that can be used to pass string data between pipeline functions and
expose methods for interacting with it.
Issue Number:
#866 
#802 
Adds key/value storage to context and includes in store & forward loop

feat(sdk): Add Storage to Context Interface

---

internal/app/configupdates.go
internal/app/configurable.go
internal/app/configurable_test.go
internal/app/service.go
internal/app/service_test.go
pkg/transforms/http.go
pkg/transforms/http_test.go

HTTP export returns HTTP response and stops pipeline on send errors. This block the ability to chain multiple HTTP exports in the pipeline to send the same data to multiple destinations.
Configurable pipeline only allows once instance of each function to be configured. Configuration names must match actual function names exactly. i.e. `HttpExport` matches `HttpExport`, but `HttpExport2` does not match `HttpExport`
Issue Number: #256
HTTP export now has option to return the input data and optionally continue pipeline on send errors. This enables the ability to chain multiple HTTP exports in the pipeline to send the same data to multiple destinations.
Configurable pipeline now supports multiple instance functions to be configured. …

feat: Add ability to chain HTTP exports for multiple destinations

---

pkg/transforms/mqttsecret.go
pkg/transforms/mqttsecret_test.go

Instead of attempting a replacement for all values in context, find
all placeholders with regexp and use matches to drive replacement
attempts.
Topic replacement is performed for all entries in context dictionary 
Issue Number: #871 
Since replacement activity is validated using a regexp, used same regexp to find placeholders actually used in topic and only attempt replacement from context for those.
- [ x] No

refactor(transforms): MQTTSecretSender Topic Replacements

---

internal/runtime/runtime.go
internal/runtime/runtime_test.go

SDK has temporary support for V1 Events which get converted to V2 Events
Issue Number: #884
Support for V1 Events has been removed
no

refactor: Remove support for V1 Events

---

internal/trigger/http/rest.go
pkg/transforms/compression_test.go
pkg/transforms/http.go
pkg/transforms/http_test.go

A few uses of the deprecated `ioutil` exist.
Issue Number: #883
No uses of the deprecated `ioutil` exist.
no

refactor: Replace use of deprecated io/ioutil with proper package

---

internal/app/backgroundmessage.go
internal/app/backgroundpublisher.go
internal/app/backgroundpublisher_test.go
internal/app/service.go
internal/app/service_test.go
internal/app/triggerfactory_test.go
internal/trigger/http/rest.go
internal/trigger/http/rest_test.go
internal/trigger/messagebus/messaging.go
internal/trigger/messagebus/messaging_test.go
internal/trigger/mqtt/mqtt.go
pkg/interfaces/backgroundmessage.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go
pkg/interfaces/trigger.go

Enable publish topic formatting for MQTT and Messagebus triggers.  Make
BackgroundPublisher API context-aware so that topics can be formatted
and delivered along with the MessageEnvelope for publication.
Issue Number: #803 
"Default" context-based topic formatting is applied when publishing to trigger outputs (including background publishing for MessageBus)
BackgroundPublisher.Publish now takes an interfaces.Context instead of correlation ID and content type.

feat(sdk): Use Default Topic Formatting for Triggers

---

internal/app/service.go
internal/app/service_test.go
internal/appfunction/context.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go

Introduce helper method to initialize an app context using the service's
dic.
Issue Number:
#900 
Introduces a helper method on Service to easily build a context using its dic

feat(sdk): Add BuildContext Method

---

internal/bootstrap/handlers/version.go
internal/bootstrap/handlers/version_test.go

Core Data is now optional, so need to use service that will always be present.
Issue Number: #902
Core Data is used for version check, but is now optional service is device services are using MessageBus and no persistence is needed/enabled.
no

refactor: Use Core Metadata Version API for version check

---

internal/trigger/mqtt/mqtt.go

ReceivedTopic not being set by MQTT Trigger
Issue Number: #909
ReceivedTopic now being set by MQTT Trigger
no

fix: Fix MQTT Trigger to set ReceivedTopic

---

internal/runtime/runtime.go
internal/runtime/storeforward.go
pkg/transforms/http.go
pkg/transforms/mqttsecret.go

Call CorrelationID API in log messages missing `()`
Issue Number:  #923
All calls CorrelationID API now proper function calls.

fix: Change logging of CorrelationID to use proper function call

---

pkg/secure/mqttfactory.go
pkg/secure/mqttfactory_test.go

MqttFactory will panic when attempt to log warning about `authMode` empty du to logger not set in the factory method.
Issue Number: #920
Logger set set in the factory method avoiding panic and logging wanring.
no

fix: Set logger in MqttFactory to avoid panic when AuthMode is empty

---

app-service-template/Attribution.txt
go.mod
internal/app/triggerfactory.go
pkg/interfaces/trigger.go

Add service.processMessageOnRuntime to use default pipeline if configured or attempt to use topic matching logic.  Deprecate TriggerMessageProcessor and TriggerContextBuilder and inline the existing functions on TriggerConfig as the approach used there will not work with multiple pipelines. Replace with MessageProcessor that only takes the message envelope and builds context(s) as needed.
Related Docs PR:
If n/a for Docs PR, state why it is not applicable:
Issue Number:
#940 
Custom triggers will be able to use the default topic -> pipeline(s) matching logic.
Only affects custom triggers, the message processor function no longer takes the app context as a parameter.   The trigger will no longer be responsible for establishing …

feat(sdk): Custom Trigger Multi-Pipeline Support

---

app-service-template/go.sum
app-service-template/main.go
app-service-template/main_test.go
internal/app/service.go
internal/app/service_test.go
internal/common/config.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/runtime/storeforward_test.go
internal/trigger/messagebus/messaging_test.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go

Match incoming topic against an array of topics when determining whether
or not to execute a given pipeline.  Allow Topics configuration as comma
separated list similar to messaging triggers.
Related Docs PR:
https://github.com/edgexfoundry/edgex-docs/pull/551
If n/a for Docs PR, state why it is not applicable:
Pipelines can only be configured to run for a single topic.
Issue Number: #945 
Pipelines can be configured with a comma-separated list of topics similar to messaging triggers.

feat(sdk): Support Multi-Topic Pipeline Configuration

---

internal/runtime/runtime.go

Fixes #951 
Signed-off-by: Jeff Titus <jeff.rtitus@gmail.com>
- None affected. All tests pass with same coverage.
- No docs change required.
Tested scenario using local build
```go
require github.com/edgexfoundry/app-functions-sdk-go/v2 v2.0.0
replace github.com/edgexfoundry/app-functions-sdk-go/v2 v2.0.0 => ../app-functions-sdk-go
```
```bash
$ http :59770/api/v2/trigger Content-Type:"application/json; charset=utf-8" action=set deviceName=SomeDevice commandName=SomeCommand resourceName=SomeResource value=45
HTTP/1.1 200 OK
Content-Length: 36
Content-Type: application/json
Date: Fri, 17 Sep 2021 18:21:19 GMT
{
"apiVersion": "v2",
"statusCode": 200
}
$ http :59770/api/v2/trigger Content-Type:"application/json" …
```

fix(runtime): ignore charset for Content-Type comparison (#951)

---

app-service-template/Dockerfile

Was golang:1.15-alpine3.14
run make docker for the app-template. It will not work.

build: Update build image for app-template to be golang:1.16-alpine3.14

---

internal/app/configurable.go
internal/app/configurable_test.go

fixes #994
Existing PR for new AES256: https://github.com/edgexfoundry/edgex-docs/pull/614
1. Build and Run ASC with this branch (i.e. update go.mod file to replace SDK)
2. Set ExecutionOder in config of sample profile to just `Encrypt`
3. Verify the error in logs is NOT the `initvector required` error
- Note there will be another error due to invalid key for aes256 which is fix in TBD PR for ASC
- 
N/A

fix: Remove initvector from require parameters for Encrypt with aes256

---

internal/app/configupdates.go
internal/app/service.go
internal/app/service_test.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/runtime/storeforward_test.go
internal/trigger/messagebus/messaging_test.go

This applies only to Configurable Pipelines
Default is properly rebuilt after error that occurred in previous configuration change are corrected.
PerTopicPipelines are properly rebuilt after any pipeline configuration changes.
fixes #998 & #999
- Run non-secure EdgeX stack with Device Virtual running
- Use this branch in ASC go.mod
- Build and run ASC with `-p=sample -cp` options
- From Consul change 
```
http://localhost:8500/ui/dc1/kv/edgex/appservices/2.0/app-sample/Wr …
```

fix: Rebuild Default and PerTopicPipelines properly after configuration changes

---

app-service-template/go.sum
go.mod
go.sum

BREAKING CHANGE: ZeroMQ no longer supported on native Windows for EdgeX
MessageBus
**N/A for Build PR**
**N/A for Build PR**

build: Update to latest go-mod-messaging w/o ZMQ on windows

---

Makefile
app-service-template/Makefile
internal/app/triggermessageprocessor.go

Includes naive fix for one race detected.
Fixes #209
- unit tests sufficient
no docs change

test(sdk): Use -race Flag when testing

---

internal/trigger/http/rest.go
internal/trigger/http/rest_test.go

After refactoring response data was not written to response
fixes #1028
unit tests sufficient
no docs change

fix(triggers): Write HTTP Response Data

---

.github/dependabot.yml
app-service-template/go.mod
app-service-template/go.sum
go.mod
go.sum

fix: Use latest 1.8.8 of redigo and ignore bad v2.0.0 tag

---

internal/app/service.go
internal/app/service_test.go
internal/common/config.go
internal/constant.go
internal/controller/rest/controller.go
internal/controller/rest/controller_test.go
internal/trigger/mqtt/mqtt.go
internal/webserver/server.go
internal/webserver/server_test.go
pkg/secure/mqttfactory.go
pkg/secure/mqttfactory_test.go
pkg/transforms/mqttsecret.go

Revert #1047
Implement the retry mechanism inside the External MQTT Trigger.
fix: #1052 #1053
Signed-off-by: Felix Ting <felix@iotechsys.com>
https://github.com/edgexfoundry/edgex-docs/pull/710
Download this [Docker Compose file](https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose.yml)
Edit the Docker Compose file to add the custom App Service's service key to EdgeX service secretstore-setup's `ADD_SECRETSTORE_TOKENS` environment variable.
```
secretstore-setup:
container_name: edgex-security-secretstore-setup …
```

fix: improper use of secretAddedSignal channel

---

internal/app/configupdates.go

Sometimes the name of a newly added configurable pipeline function may start with one of the existing function names. For example, user is unaware of the existence of AddTags, implements function AddTagsFromDeviceResource and uses it in App Service configuration. In this case, sdk will resolve it as the function AddTags.
To make the result more accurate, the findMatchingFunction should try to find if there is a function with name identical to the target configuration function first. If no match, then iterate over all the functions to see if the target configuration function name starts with actual function name. If there are multiple matches then pick the one with the longest name.
Signed-off-by: Felix Ting <felix@iotechsys.com>
**If your build fails**  due to your commit message not …

feat: Optimize findMatchingFunction

---

app-service-template/go.mod
app-service-template/go.sum
app-service-template/res/configuration.toml
go.mod
go.sum
internal/app/service_test.go
internal/app/triggerfactory.go
internal/app/triggerfactory_test.go
internal/app/triggermessageprocessor.go
internal/app/triggermessageprocessor_test.go
internal/constant.go
internal/runtime/runtime.go
internal/runtime/storeforward_test.go
pkg/interfaces/service.go

closes #1085
**TBD**
Run non-secure edgex stack with device virtual
Build and run template app from this branch with DEBUG logging
Verify the logs show 4 different pipeline metrics registered
Verify every 30secs, the logs show 6 metrics reported.

feat: Added initial SDK level App service metrics

---

app-service-template/go.mod
app-service-template/go.sum
go.mod
go.sum
internal/app/triggerfactory.go
internal/runtime/runtime.go

TBD
Build App Template with module from this branch
Run from command line with DEBUG logging and verify 8 metrics being reported.
Run ASC with metrics-influxdb using the following command
```
./app-service-configurable -p=metrics-influxdb | grep "Transformed Metric to"
```
Verify logs contain metrics with the names from App Templates Config and tags for the pipeline ids
```
'PipelineMessagesProcessed,service=new-app-service,pipeline=Floats counter-count=14 …
```

feat: Add pipeline IDs as tags to the metrics collected for each pipeline

---

app-service-template/Attribution.txt
app-service-template/go.mod
app-service-template/go.sum
go.mod
go.sum
pkg/transforms/jsonlogic.go

They have now fixed thier go.mod issue allow us to use V3 release tags
**N/A**
**N/A**

build: Upgrade to latest V3 JSON Logic

---

internal/app/triggermessageprocessor.go
internal/app/triggermessageprocessor_test.go

Context used in response handler needs to match context used for
pipeline execution.  Fixes #1010 for jakarta.
Co-authored-by: Lenny Goodell <leonard.goodell@intel.com>
This is a bugfix backport for jakarta no new code.

fix(triggers): Pass Child Context to Response Handler [JAKARTA]

---

app-service-template/res/configuration.toml
go.sum
internal/app/triggermessageprocessor_test.go
internal/constant.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
pkg/interfaces/service.go

applies to #1116
Small bit of refactoring so `lc` (logging client) is available from struct instead of DIC
Run edgex with MQTT Messagebus 
Run app template with new metric enabled and configured for MQTT Messagebus
Send message using MQTT.fx that causes error in all 3 pipelines
Run ASC with metrics-influxdb profile configured for MQTT Messagebus
Verify logs shows the PipelineProcessingErrors metric for of the 3 pipelines with the specific pipeline as a …

feat: Add metric to capture count of errors from function pipelines

---

internal/app/configurable.go
pkg/transforms/event.go
pkg/transforms/event_test.go

closes #1149
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
[https://github.com/edgexfoundry/edgex-docs/pull/799](https://github.com/edgexfoundry/edgex-docs/pull/799)
1. run the base edgex components
2. set the following changes in the sample profile
```
[Writable.Pipeline]
ExecutionOrder = "Compress, WrapIntoEvent, SetResponseData"
...
[Writable.Pipeline.Functions.WrapIntoEvent]
[Writable.Pipeline.Functions.WrapIntoEvent.Parameters]
ProfileName = "MyProfile"
DeviceName = "MyDevice"
ResourceName = "XMLEvent" …
```

feat: add ability to wrap data into an event

---

pkg/secure/mqttfactory.go
pkg/secure/mqttfactory_test.go

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
Closes #1096
1. Check out edgex-examples application-services/custom/cloud-export-mqtt 
2. Apply the fix for https://github.com/edgexfoundry/edgex-examples/issues/133
3. Spin up a new mqtt broker with server-side TLS (details elided)
4. Create a custom `configuration.toml` based on the existing example.  Set a value for the `cacert` MQTT secret and set `AuthMode = "cacert"`.
```
[Writable.InsecureSecrets.mqtt.Secrets]
cacert = '''
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
'''
[MqttExportConfig]
BrokerAddress = "mqtts://localhost:1883"
AuthMode = "cacert"
```
5. With the original code, the following error would be emitted
```
level=ERROR …
```

fix: When MQTT authmode=cacert, set RootCAs on TLS config

---

internal/app/configupdates.go
internal/runtime/runtime.go

fixes #1187
Run non-secure EdgeX stack
Build ASC with SDK from this PR
Run ASC with profile sample and -cp option
Verify Float pipeline is executed when topic matches
Change topic for Float pipeline from Consul to something that will never match
Verify Float pipeline is never executed when topic would have matched previously

fix: Update Pipeline topics when writable pipeline changed

---

pkg/secure/mqttfactory.go
pkg/secure/mqttfactory_test.go

Username may be required when MQTT cert authentication.
Signed-off-by: Ian <ancientxu@gmail.com> 
If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-functions-sdk-go/blob/main/.github/CONTRIBUTING.md
```toml
[Writable]
LogLevel = "INFO"
[Writable.StoreAndForward]
Enabled = false
RetryInterval = "5m"
MaxRetryCount = 10
[Writable.InsecureSecrets]
[Writable.InsecureSecrets.DB]
path = "redisdb"
[Writable.InsecureSecrets.DB.Secrets]
username = ""
password = ""
[Writable.InsecureSecrets.mqtt]
path = "mqtt"
[Writable.InsecureSecrets.mqtt.Secrets]
username = "device1.azure-devices.net/device1/?api-version=2021-04-12" …
```

fix: Username may be required when MQTT cert authentication

---

internal/app/service.go
internal/app/service_test.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/runtime/storeforward_test.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go

We are developing an application-service without Consul, but we also want to configure the pipelines dynamically according to a local file or other system(such as k8s configmap). We expect to expose the Set and Clear operation of pipelines so that achieving our goals.
Just use unit tests is ok.

feat: Expose Set and Clear operation of pipelines in ApplicationService interface

---

app-service-template/go.mod
app-service-template/go.sum
internal/app/service.go
internal/app/service_test.go
internal/app/triggermessageprocessor.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/runtime/storeforward.go
internal/runtime/storeforward_test.go

refactor: Renamed GolangRuntime to FunctionPipelineRuntime

---

app-service-template/functions/sample.go
app-service-template/go.mod
app-service-template/go.sum
go.mod
go.sum
internal/app/service.go
internal/constant.go

BREAKING CHANGE: Location of service's configuration in Consul has changed
closes #1236
This PR is dependent on the following PR to be merged first then update the go.mod
- https://github.com/edgexfoundry/go-mod-bootstrap/pull/401
- https://github.com/edgexfoundry/go-mod-core-contracts/pull/776
Build and run app template with edgex stack running
Verify the service configuration is pushed to `edgex/3.0/app-new-service`

refactor!: Use config stem from common constants

---

internal/app/triggerfactory.go
internal/app/triggermessageprocessor.go
internal/trigger/messageprocessor.go
pkg/interfaces/trigger.go

BRAKING CHANGE: remove deprecated Process code and MessageProcessor  code, use MessageReceived
CLoses: #1227
TBD
make test 
N/A

refactor(sdk): remove deprecated Process code

---

Makefile
app-service-template/Makefile
app-service-template/go.mod

Docker builds were failing localy, but not in pipeline.
cd app-template
run `make docker`
Verify builds successfully

build: Disable CGO for all docker builds so always work

---

internal/app/service.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go

BREAKING CHANGE: remove deprecated StoreSecret code, use SecretProvider
Closes: #1224
https://github.com/edgexfoundry/edgex-docs/pull/929
make test

refactor(sdk): remove deprecated StoreSecret code

---

pkg/transforms/http.go

closes: #1266
`cd edgex-compose/compose-builder`
`make run no-secty ds-virtual`
`cd app-service-configurable`
./app-service-configurable  -p functional-test
--> open new terminal
`./app-service-configurable  -p sample  -cp`
change httpExport  url in consul to Http://localhost:59705/api/v2/trigger
changed execution order in consul to HTTPExport
verified that metric for HTTPExport was reported

fix: correct the metric name  that is registered

---

internal/runtime/runtime.go
internal/runtime/runtime_test.go

refactor(sdk): implement error interface for MessageError

---

app-service-template/main.go
app-service-template/res/configuration.toml
internal/app/service.go
internal/app/service_test.go
internal/runtime/runtime.go
internal/runtime/runtime_test.go
internal/trigger/messagebus/messaging.go
internal/trigger/messagebus/messaging_test.go

BREAKING CHANGE: All subcribe and publish topics now have the configured base topic (`edgex/` by default) prepened automatically. Configured topics and topics in code need to have "edgex/" removed.
Run non-secure edgex with Device Virtual and mqtt-broker
Build App Template from this branch
Run `./app-new-service -cp` with DEBUG logging
Verify the following are in the log message and `edgex` isn't duplicated in the topics logged.
```
msg="Pipeline 'Floats' added for topics …
```

feat!: Prepend base topic to all topics

---

app-service-template/go.mod
app-service-template/go.sum
go.mod
go.sum
internal/controller/rest/controller.go
internal/controller/rest/controller_test.go

BREAKING CHANGE: secret DTO object in core contracts uses SecretName instead of Path
`make test`

refactor!: Consume Secret DTO changes

---

internal/webserver/server.go

When enabling HTTPS, the web server would try to use dic, but it was never set in the` NewWebServer()` function. This would result in a nil pointer panic when trying to access Vault.
Also, a tls.Config was created because `ListenAndServeTLS` requires the filename and path of a certificate and key but the raw certificate and key data was retrieved from Vault. Leaving the cert and key as empty strings uses the certificate in tls.Config.
Fixes: #1315
1. Setup a HTTPS web server following this …

fix(webserver): fix a nil pointer crash when enabling the https web server

---

Jenkinsfile
openapi/v3/README.md
openapi/v3/app-functions-sdk.yaml

BREAKING CHANGE: Swagger for API reference has been move to 3.0.0

feat!: Move swagger to v3

---

pkg/transforms/compression.go

fixes #1250
Using App Sample set all pipelines to just `Compression` (gzip)
Run with non-secure EdgeX stack with Device Virtual
Verify after 30 mins that the panic has been fixed.
Change Compression to be `zlib` and rerun test

fix: Make Compression functions thread safe

---

internal/app/service_test.go
internal/appfunction/context_test.go
internal/bootstrap/handlers/version_test.go
internal/controller/rest/controller.go
internal/runtime/runtime_test.go

refactor: Clean up all remaining reverences to v2 in the code

---

app-service-template/main.go
app-service-template/main_test.go
internal/app/service.go
internal/app/service_test.go
pkg/interfaces/mocks/ApplicationService.go
pkg/interfaces/service.go

Use the App Context in custom app service to exit long running functions when the context is canceled due to termination signal.
- [x ] I have opened a PR for the related docs change (if not, why?)
https://github.com/edgexfoundry/edgex-docs/pull/1149
Build and run the App Template
Verify no errors.

feat: Add API to get SDK's App Context

---

app-service-template/go.mod
app-service-template/go.sum
go.mod
go.sum
internal/app/service.go
internal/app/triggerfactory.go
internal/bootstrap/handlers/version.go
internal/trigger/messagebus/messaging.go

with better error message handling from the go-mod-bootstrap PR, there is some logic needs to be fixed to avoid the app being crashed.
Closes: #1443
[relate to go-mod-bootstrap issue](https://github.com/edgexfoundry/go-mod-bootstrap/issues/564) when common config is missing from command line.

feat: fix logic to better error handling when common config is missing when runs in hybrid mode

---

internal/app/service_test.go
pkg/interfaces/service.go

Closes #1437
Additionally adds error checks to unit tests
"make test"

fix(security): Mark AddRoute(unauthenticated) as Deprecated

---

Jenkinsfile
internal/app/service_test.go
internal/webserver/server.go
internal/webserver/server_test.go

BREAKING CHANGE: EdgeX standard routes will require authentication. AddCustomRoute is a new interface method that enables adding authenticated routes.
<[link to docs PR](https://github.com/edgexfoundry/edgex-docs/pull/1169)>

feat(security): Add authentication hooks to routes (backport)

---

internal/constant.go
pkg/transforms/helpers.go
pkg/transforms/helpers_test.go
pkg/transforms/http.go
pkg/transforms/http_test.go
pkg/transforms/mqttsecret.go

closes #1467
github.com/edgexfoundry/edgex-docs/pull/1237
Run non-secure EdgeX stack with device REST
Build ASC with this branch of the SDK
Add the following to `http-export` profile under `Writable`
```
Telemetry:
Interval: "5s"
Metrics:
HttpExportErrors: true
```
Set URL under `HTTPExport` to 
```
Url: "me:junk@http://nowhere.com/nodata"
```
Run ASC 
```
WRITABLE_LOGLEVEL=DEBUG ./app-service-configurable -p=http-export -cp -d
```
Send data thru Device Rest
Verify following logs
```
level=DEBUG ts=2023-09-25T23:27:11.549514342Z …
```

feat: Add error metrics for HTTP and MQTT export errors

---

internal/common/config.go
internal/trigger/mqtt/mqtt.go

closes #1117
TBD one refactor PR is merged
Run edgex Stack
```
make run mqtt-broker mqtt-verbose no-secty
```
Build ASC with the SDK from this branch
Modified `external-mqtt-trigger` profile to add the following to `Trigger.ExternalMqtt` section
```
Will:
Enabled: true
Payload: "goodbye"
Qos: 2
Retained: true
Topic: "me/be/gone"
```
Run ASC
```
./app-service-configurable -d -cp -p=external-mqtt-trigger
```
Verify the following is in log file.
```
msg="Last Will options set for MQTT Trigger: {Enabled:true Payload:goodbye Qos:2 …
```

feat: Add Will configuration elements for External MQTT trigger config

---

app-service-template/go.mod
app-service-template/go.sum
internal/app/configurable.go
internal/app/configurable_test.go
internal/app/service_test.go
pkg/transforms/mqttsecret.go

closes #1117
TBD
run non-secure edgex as follows
```
make run mqtt-broker mqtt-verbose no-secty ds-rest
```
Build ASC with this branch
Add the following to `mqtt-export` profile under `MQTTExport.Parameters`
```
WillEnabled: "true"
WillPayload: "goodbye"
WillQos: "2"
WillRetained: "true"
WillTopic: "me/be/gone"
```
run ASC as follows
```
./app-service-configurable -d -o -cp -p=mqtt-export
```
Verify expected 5 Will parameters are in following log message
```
configurable pipeline with parameters: [secretname='mqtt', willqos='2', …
```

feat: Add MQTT Will configuration for MQTT Export

---

internal/trigger/messagebus/messaging.go

This is now handled by the MessageBus bootstrap handler.
closes #1479
build ASC with NATS capability locally (non-docker) with this branch of the SDK
Build edgex-go Docker with NATS capability
Build Device Virtual Docker for NATS
Run non-secure EdgeX stack with NATS Bus
```
make run ds-virtual no-secty nats-bus
```
Stop app-rules-engine container
Verify app-rules-engine no longer fails with "already connected to NATS" message
Run ASC with NATS locally
```
./app-service-configurable -cp -d -p rules-engine
``` …

fix: Remove attempt to connect to the MessageBus from trigger

---

README.md

docs: [SDK] Update README for new doc structure

---

app-service-template/go.mod
app-service-template/go.sum
internal/app/configurable.go
internal/app/configurable_test.go
internal/app/service.go
internal/app/service_test.go
pkg/transforms/mqttsecret.go

Performance enhancement for when service is processing many events very fast causing back ups when using lazy connection.
closes #1516
TBD
Run non-secure edgex stack with Device Virtual and MQTT Broker
```
make run no-secty ds-virtual mqtt-broker
```
Comment out existing pipeline function init code in app template
Add the following pipeline function int code
```go
export := transforms.NewMQTTSecretSender(mqttConfig, false)
export.ConnectToBroker(app.service.LoggingClient(), app.service.SecretProvider(), 5, time.Second*3)
err := …
```

feat: Add capability to pre-connect to MQTT Broker for MQTT Export

---

internal/appfunction/context.go
internal/runtime/runtime.go
internal/runtime/storeforward.go
internal/runtime/storeforward_test.go
pkg/interfaces/context.go
pkg/interfaces/mocks/AppFunctionContext.go
pkg/transforms/http.go
pkg/transforms/mqttsecret.go

closes #1526
https://github.com/edgexfoundry/edgex-docs/pull/1328
Run non-secure Edgex stack with Device Rest and MQTT Broker from compose builder
```
make run no-secty ds-rest mqtt-broker
```
Build ASC with this branch of APP SDK
Modify the ASC mqtt-export profile as follows:
- Enable Store and Forward
```
StoreAndForward:
Enabled: true
```
- Set MaxReconnectInterval for MQTT Export
```
MaxReconnectInterval: "5s"
```
- Enable PersistOnError for MQTT Export
```
PersistOnError: "true"
```
Run ASC with DEBUG logging
``` …
```

feat: Add retry on success capability for Store and Forward

---

internal/constant.go
internal/runtime/storeforward.go
internal/runtime/storeforward_test.go

feat: Add metric for Store And Forward queue size

---

internal/runtime/storeforward_test.go
pkg/transforms/helpers.go
pkg/transforms/helpers_test.go
pkg/transforms/http.go
pkg/transforms/mqttsecret.go

fix: Handle race condition when lazy registering export metrics

---

internal/webserver/server.go

while reviewing code, noticed two errors that were erroneously used

fix: return correct errors

---

app-service-template/Makefile

fix: Only one ldflags flag is allowed

---

app-service-template/go.mod
go.mod

Per https://github.com/dependabot/dependabot-core/issues/11825 and https://github.com/dependabot/dependabot-core/pull/11826 , the dependabot has been updated to use GOTOOLCHAIN=go1.24.1 and it will add toolchain in go mod tidy when the go directive is specified with language version(1.N). As we don't want to the toolchain to be specified with go1.24.1, change the go directive to released version(1.N.P).

build(deps): update go directive to released version

---

pkg/transforms/metrics.go
pkg/transforms/metrics_test.go

Replace fmt.Sprintf("%v",v) with cast.ToString(v) to ensure consistent string conversion and avoid scientific notation for float values.
fix: #1744 

fix: Replace fmt.Sprintf("%v",v) with cast.ToString(v)
